þL÷þHJLôþGGGEL
þ@FGDDGI[þA@BDCEGGI[þBA@BBDBFEHþB@@@B@BBEDBI
þ@@@@@C@@@EDBG[þHDGJG@@@B@CCAEH	þJHFJJGGI@BCB@@FI	
[þ
JHGEHHGIJJJJG@BFVTTU
þJJGGHJJGIJJHEEHIWSTTTT–þHIGGHHJIGIHGGGE[W

UST–þSUW	
JJJIHI[[


[[
WVWVUþWWWVUTTTTUUVW	
÷[	WWUSU
	WWT°RUVW÷÷ò
W	T°VUþWV°T	[
W
[ððò[
W
TUþTôô÷[W[[ò÷ôò[[
VU[þ
ðô÷	
[äð
ôò[÷ôòòòôþ÷8	UVòò÷ôòò÷÷ôôþ6689òä6358HGþ654338÷÷þ÷÷÷÷ÿþL÷þLJLôþJIIEL
þDIHEEGI[þFCGGDHJJI[þHFCGHFHJIIþGEDED@DCHIEI
þ@DDD@D@@@EIDI[þDBDFG@@@D@DIDEH	þBBBCDBBC@DIHEEHI	
[þ
D@@ACBADEEGGEEHIVTTU
þIJG@BBB@DFFFEEHIWSTTTT–þHHGHH@@@@DFGGGE[W

UST–þSUW	
HHBCDE[[


[[
WVWVUþWWWVUTTTTUUVW	
÷[	WWUSU
	WWT°RUVW÷÷ò
W	T°VUþWV°T	[
W
[ððò[
W
TUþTôô÷[W[[ò÷ôò[[
VU[þ
ðô÷	
[äð
ôò[÷ôòòòôþ÷8	UVòò÷ôòò÷÷ôôþ6689òä6358HGþ654338÷÷þ÷÷÷÷ÿþL÷þLJLôþJIIEL
þDIHEEGI[þFCGGDHJJI[þHFCGHFHJIIþGEDEEBECHIEI
þBCCDBEC@BEIDI[þHDGHIB@BEBEIDEH	þDHFHHFEEBEIHEEHI	
[þ
@@@EHHEGHIIGEEHIVTTU
þIHD@DJJEGIIHEEHIWSTTTT–þHGEEHHIEGIHGGGE[W

UST–þSUW	
HHHHHI[[


[[
WVWVUþWWWVUTTTTUUVW	
÷[	WWUSU
	WWT°RUVW÷÷ò
W	T°VUþWV°T	[
W
[ððò[
W
TUþTôô÷[W[[ò÷ôò[[
VU[þ
ðô÷	
[äð
ôò[÷ôòòòôþ÷8	UVòò÷ôòò÷÷ôôþ6689òä6358HGþ654338÷÷þ÷÷÷÷ÿþL÷þLJLôþJIIEL
þDIHEEGI[þFCGGDHJJI[þHFCGHFHJIIþGEDEGDGCHIEI
þDCCDDIDACEIDI[þHDGHIDADGDIIDEH	þEHFHHFEEDGIHEEHI	
[þ
B@BEHHEGHIIGEEHIVTTU
þIHEBEJJEGIIHEEHIWSTTTT–þHGEEHHIEGIHGGGE[W

UST–þSUW	
HHHHHI[[


[[
WVWVUþWWWVUTTTTUUVW	
÷[	WWUSU
	WWT°RUVW÷÷ò
W	T°VUþWV°T	[
W
[ððò[
W
TUþTôô÷[W[[ò÷ôò[[
VU[þ
ðô÷	
[äð
ôò[÷ôòòòôþ÷8	UVòò÷ôòò÷÷ôôþ6689òä6358HGþ654338÷÷þ÷÷÷÷ÿþL÷þLJLôþJIIEL
þDIHEEGI[þFCGGDHJJI[þHFCGHFHJIIþGEDEGEGCHIEI
þDCCDEIECCEIDI[þHDGHIECEGEIIDEH	þGHFHHFEEEGIHEEHI	
[þ
DADEHHEGHIIGEEHIVTTU
þIHGDGJJEGIIHEEHIWSTTTT–þHGEEHHIEGIHGGGE[W

UST–þSUW	
HHHHHI[[


[[
WVWVUþWWWVUTTTTUUVW	
÷[	WWUSU
	WWT°RUVW÷÷ò
W	T°VUþWV°T	[
W
[ððò[
W
TUþTôô÷[W[[ò÷ôò[[
VU[þ
ðô÷	
[äð
ôò[÷ôòòòôþ÷8	UVòò÷ôòò÷÷ôôþ6689òä6358HGþ654338÷÷þ÷÷÷÷ÿþL÷þLJLôþJIIEL
þDIHEEGI[þFCGGDHJJI[þHFCGHFHJIIþGEDEGFGCHIEI
þDCCDFIFFCEIDI[þHDGHIHEEGFIIDEH	þIHFHHFEEGGIHEEHI	
[þ
ECEEHHEGHIIGEEHIVTTU
þIHGEHJJEGIIHEEHIWSTTTT–þHGEEHHIEGIHGGGE[W

UST–þSUW	
HHHHHI[[


[[
WVWVUþWWWVUTTTTUUVW	
÷[	WWUSU
	WWT°RUVW÷÷ò
W	T°VUþWV°T	[
W
[ððò[
W
TUþTôô÷[W[[ò÷ôò[[
VU[þ
ðô÷	
[äð
ôò[÷ôòòòôþ÷8	UVòò÷ôòò÷÷ôôþ6689òä6358HGþ654338÷÷þ÷÷÷÷ÿþL÷þLJLôþJIIEL
þDIHEEGI[þFCGGDHJJI[þHFCGHFHJIIþGEDEGHGCHIEI
þDCCDFIFGCEIDI[þHDGHIHGEGHIIDEH	þIHFHHFEEGGIHEEHI	
[þ
GEGEHHEGHIIGEEHIVTTU
þIHGEHJJEGIIHEEHIWSTTTT–þHGEEHHIEGIHGGGE[W

UST–þSUW	
HHHHHI[[


[[
WVWVUþWWWVUTTTTUUVW	
÷[	WWUSU
	WWT°RUVW÷÷ò
W	T°VUþWV°T	[
W
[ððò[
W
TUþTôô÷[W[[ò÷ôò[[
VU[þ
ðô÷	
[äð
ôò[÷ôòòòôþ÷8	UVòò÷ôòò÷÷ôôþ6689òä6358HGþ654338÷÷þ÷÷÷÷ÿþI÷þDDHôþDCC@G
þ@CB@@BC[þHGFD@BDDC[þIIFJJHJJIIþHGFFGHGEHJGI
þEDDEFIFFEGJFI[þHDGHIHGEGHIIFGH	þIHFHHFEEGGIHEEHI	
[þ
IGGEHHEGHIIGEEHIVTTU
þIHGEHJJEGIIHEEHIWSTTTT–þHGEEHHIEGIHGGGE[W

UST–þSUW	
HHHHHI[[


[[
WVWVUþWWWVUTTTTUUVW	
÷[	WWUSU
	WWT°RUVW÷÷ò
W	T°VUþWV°T	[
W
[ððò[
W
TUþTôô÷[W[[ò÷ôò[[
VU[þ
ðô÷	
[äð
ôò[÷ôòòòôþ÷8	UVòò÷ôòò÷÷ôôþ6689òä6358HGþ654338÷÷þ÷÷÷÷ÿþ[
WW	WWUUWWþ
W	VUUUUVUWþ
WVTUUUUW
VþWVTUUUU[

þ[[[	þ[[[[þ[[[[þ[þ>þ
þ
þ[
þHH[þII
þHII

þII[

L[
þ[I	W[[LJ[		þ
WVW[[
[[[JJ[VV	þ
VVV		
		

[LJJ[VTTU
þUVWWWWWWW	
LLIIJWSTTTTW	þRSTUUVVWWW
JJJJJ

USTTTVTþSUW	
TUW
[JJJIIJJJ[
WVRTTVSþWWWVUTTTVVVVWôôòô÷IIJ[	WWWRTWT
	WWT°RUVW


[JII÷ôò÷

WW	T°
	þWV°T	[
W


JJ÷÷÷÷÷ò
ð
WW
TUþ	[[W[[[÷÷÷÷ôðôòVU
[þ
ô÷÷÷÷[[

÷ôððò÷UUUþ÷ô÷÷[


ôäòô÷[Wþ÷ôôä—HJ÷òäðòþôðP—GH÷÷þ™§Gÿþ	SUW[þ÷þW°°°TW	[þL÷äôþ	R°°°°TW
[[þHJLôòò	T°°°°SWV[[[[þ
GGGEL

÷UR°°°RUWW[[[[þ@FGDDGI[	WT°°°°SWV
[[[þA@BDCEGGI[VVT°°°°UWV
[[þBA@BBDBFEHSUU°°°RWVW[[[þB@@@B@BBEDBI
VRTS°RUWU	[[@@@@@C@@@EDBG[	VR°SUWVU
[þG@@@B@CCAEH	
	VT°RSTVWW


þ@BCB@@FI	
[
WUW3VUSSRRTþ
G@BFVTTU

VUWÑ5DWUWþWSTTTT–	WV	Ñ5@WþST–WW	Ñ8þWVUT–W5þSUVUÿþ	SUW[þ÷þW°°°TW	[þL÷äôþ	R°°°°TW
[[þLJLôòò	T°°°°SWV[[[[þ
JIIEL

÷UR°°°RUWW[[[[þDIHEEGI[	WT°°°°SWV
[[[þFCGGDHJJI[VVT°°°°UWV
[[þHFCGHFHJIISUU°°°RWVW[[[þGEDED@DCHIEI
VRTS°RUWU	[[@DDD@D@@@EIDI[	VR°SUWVU
[þG@@@D@DIDEH	
	VT°RSTVWW


þ@DIHEEHI	
[
WUW3VUSSRRTþ
EEHIVTTU

VUWÑ5DWUWþWSTTTT–	WV	Ñ5@WþST–WW	Ñ8þWVUT–W5þSUVUÿþ	SUW[þ÷þW°°°TW	[þL÷äôþ	R°°°°TW
[[þLJLôòò	T°°°°SWV[[[[þ
JIIEL

÷UR°°°RUWW[[[[þDIHEEGI[	WT°°°°SWV
[[[þFCGGDHJJI[VVT°°°°UWV
[[þHFCGHFHJIISUU°°°RWVW[[[þGEDEEBECHIEI
VRTS°RUWU	[[BCCDBEC@BEIDI[	VR°SUWVU
[þIB@BEBEIDEH	
	VT°RSTVWW


þBEIHEEHI	
[
WUW3VUSSRRTþ
EEHIVTTU

VUWÑ5DWUWþWSTTTT–	WV	Ñ5@WþST–WW	Ñ8þWVUT–W5þSUVUÿþ	SUW[þ÷þW°°°TW	[þL÷äôþ	R°°°°TW
[[þLJLôòò	T°°°°SWV[[[[þ
JIIEL

÷UR°°°RUWW[[[[þDIHEEGI[	WT°°°°SWV
[[[þFCGGDHJJI[VVT°°°°UWV
[[þHFCGHFHJIISUU°°°RWVW[[[þGEDEGDGCHIEI
VRTS°RUWU	[[DCCDDIDACEIDI[	VR°SUWVU
[þIDADGDIIDEH	
	VT°RSTVWW


þDGIHEEHI	
[
WUW3VUSSRRTþ
EEHIVTTU

VUWÑ5DWUWþWSTTTT–	WV	Ñ5@WþST–WW	Ñ8þWVUT–W5þSUVUÿþ	SUW[þ÷þW°°°TW	[þL÷äôþ	R°°°°TW
[[þLJLôòò	T°°°°SWV[[[[þ
JIIEL

÷UR°°°RUWW[[[[þDIHEEGI[	WT°°°°SWV
[[[þFCGGDHJJI[VVT°°°°UWV
[[þHFCGHFHJIISUU°°°RWVW[[[þGEDEGEGCHIEI
VRTS°RUWU	[[DCCDEIECCEIDI[	VR°SUWVU
[þIECEGEIIDEH	
	VT°RSTVWW


þEGIHEEHI	
[
WUW3VUSSRRTþ
EEHIVTTU

VUWÑ5DWUWþWSTTTT–	WV	Ñ5@WþST–WW	Ñ8þWVUT–W5þSUVUÿþ	SUW[þ÷þW°°°TW	[þL÷äôþ	R°°°°TW
[[þLJLôòò	T°°°°SWV[[[[þ
JIIEL

÷UR°°°RUWW[[[[þDIHEEGI[	WT°°°°SWV
[[[þFCGGDHJJI[VVT°°°°UWV
[[þHFCGHFHJIISUU°°°RWVW[[[þGEDEGFGCHIEI
VRTS°RUWU	[[DCCDFIFFCEIDI[	VR°SUWVU
[þIHEEGFIIDEH	
	VT°RSTVWW


þGGIHEEHI	
[
WUW3VUSSRRTþ
EEHIVTTU

VUWÑ5DWUWþWSTTTT–	WV	Ñ5@WþST–WW	Ñ8þWVUT–W5þSUVUÿþ	SUW[þ÷þW°°°TW	[þL÷äôþ	R°°°°TW
[[þLJLôòò	T°°°°SWV[[[[þ
JIIEL

÷UR°°°RUWW[[[[þDIHEEGI[	WT°°°°SWV
[[[þFCGGDHJJI[VVT°°°°UWV
[[þHFCGHFHJIISUU°°°RWVW[[[þGEDEGHGCHIEI
VRTS°RUWU	[[DCCDFIFGCEIDI[	VR°SUWVU
[þIHGEGHIIDEH	
	VT°RSTVWW


þGGIHEEHI	
[
WUW3VUSSRRTþ
EEHIVTTU

VUWÑ5DWUWþWSTTTT–	WV	Ñ5@WþST–WW	Ñ8þWVUT–W5þSUVUÿþ	SUW[þ÷þW°°°TW	[þI÷äôþ	R°°°°TW
[[þDDHôòò	T°°°°SWV[[[[þ
DCC@G

÷UR°°°RUWW[[[[þ@CB@@BC[	WT°°°°SWV
[[[þHGFD@BDDC[VVT°°°°UWV
[[þIIFJJHJJIISUU°°°RWVW[[[þHGFFGHGEHJGI
VRTS°RUWU	[[EDDEFIFFEGJFI[	VR°SUWVU
[þIHGEGHIIFGH	
	VT°RSTVWW


þGGIHEEHI	
[
WUW3VUSSRRTþ
EEHIVTTU

VUWÑ5DWUWþWSTTTT–	WV	Ñ5@WþST–WW	Ñ8þWVUT–W5þSUVUÿ[
WW	WWUUWWþ
W	VUUUUVUWþ
WVTUUUUW
VþWVTUUUU[

Vþ[[[	Wþ[[[[
þ[[[[[þ[þ[[þþ[
[þþ	þ
áþ[[	þ

÷ôòPþ[W[þ[
ôòðáW[þHH[PòôðW[þII
ô[áð	þHII

W
ô	II[

L[
	W
[þ[[LJ[		VU[
WWW


þ[[JJ[VV	WRWWSRRTþ
LJJ[VTTU
	VRW	[VWWþWSTTTTW	
	VTV8[WþSTTTVT
WUW	5þTTVST	W	þWT	[ÿþòô˜þPPPááðþððäääðòþòðôô÷÷÷÷ôôôô÷þòðáò÷÷ù÷ôòòô÷ù™¨þ
òðPòôPô÷ôòPô÷˜þòðääò÷ù÷òáò÷ùù÷ðáòôù÷÷÷÷òþòðPPðPòôääô÷ää÷ôPòôP÷òääðPPþôðPPðáðô÷ù÷òPòô÷÷÷òPðPPþôðPPðáòðPòôáôòääðPþ
ôðPPðPðôù÷òáðPPþôðPPðáðòääðPPþôðPPðPðPPþôðPPPPþôðPPÿþ[
þUW[	þ		UWWTþUUW	
UWTþôô÷÷÷÷ôòððþòäðððò–þ–¥GH÷ôô÷—÷þòô÷¥—–—÷ôRþòäáäðòô÷÷÷÷ôôôò	óþôòðääðGôô§ôòðñ8;þ
§÷÷ôòðð8G§÷98;Gþ™ùù÷òôô÷÷÷ô55–—H§HGþòðòò÷÷÷ù÷òòô÷÷÷959G–
þòðPòôPô÷ôòPðò;888;KðPPþòðääò÷ù÷òáò÷ùù÷ðáòôù÷÷òPôðòðPPðPòôääô÷ää÷ôPòôP÷òääðPPþôðPPðáðô÷ù÷òPòô÷÷÷òPðPPþôðPPðáòðPòôáôòääðPþ
ôðPPðPðôù÷òáðPPþôðPPðáðòääðPPþôðPPðPðPPþôðPPPPþôðPPÿþ°RTTþUWU°TTTTþ	UWWURTTTTUþGHJWUW	URTTTUUòþ99HH9WUðUTURRôòþ
÷÷÷ô85689òðäRà÷÷÷þòðäòòð546ñàQQàQRQ÷ù©¨§þòððäòôä;ññQRRQ¨§§ôòðäþôò÷ôòòððäðQððñðôôòðäþ÷ôòòðääðòôóRðó		ôòäþ
÷ôôôôòòòô÷ù§ó	ô	ôððþ÷÷©©©§™˜óôôðäþ§™˜óðððäþ¨÷÷òñòäþôðÿþ[[þþ[
[þ	þ[[	þ[W[þW[þW[þ	þþ>	WþUW
þW
[þWWWW	
þ
W	VWWWW[þ8B
	WVUSUW
þ	
4D[	WVSV[[þ
[4DF[		TWþ[
[[48BG		V[HJþUW[	TT
DF[
VIGHI÷þ
		UWWTTTW
WCG÷ô÷÷÷÷H–—þUUW	
UWTTW—WVVDE÷ðäòô÷HGþôô÷÷÷÷ôòðð—–QààKJFDFG÷HGþòäðððò–	RàQLJJIHGIþ–¥GH÷ôô÷—÷àQRIHG–—Hôðòô÷¥—–—÷ôRààQóGIKääðPPþäðòô÷÷÷÷ôôôò	óQRð

òPðPPþðGôô§ôòðñ8;óñ
òääðPþ
G§÷98;Gð
áðPPþ—H§HG

äðPPþ–
ð	ðPPþKðPPPPþôðPPÿþ	SUW[þ÷þW°°°TW	[þ	R°°°°TW
[[þ°°°°SWV[[[[þ°RUWW[[[[[þWV
[[[
[þ
[[
[[þ[
[
þ[
þ[
[þ	W
þUW
[þW
[[þUVWW	
[[[ô÷þ@WVVWWWW[[
÷÷òôþ
4	@WWVUSUW
[	÷òòòPþ638[BDWVSV÷[
	H÷ôôù÷÷òPþSSU59EBWW—I[II–K÷ð÷òääðPPþTU÷HBDG÷JHKIG–K÷÷òðäðPPþUGIFBòðô÷H—–GK÷ôòääðPþ
–òðäò©§¨÷òáðPPþðäðô¨˜©÷ääðPPþðô_§˜ôäòPPþ_¨™¨ôPPþ¨ôðPÿþ[[þþ[
[þ	þ[[	þ[W[[þW[
[þW[
[[þ	[
[
þ
[
þ[
[þ	W
þUW
[þW
[[þWWWW	
[[ô÷þ
W	VWWWW[[
÷ôòôþ
8B
	WVUSUW
[	÷÷÷òPþ	
4D[	WVSV[[
	HG—HôôôòPþ
[4DF[		TW[ù÷÷HG—HôòðPPþ48BG		V[HJù÷÷÷÷ô÷÷—ôPPþDF[
VIGHI÷÷ôô÷ôòääðPþ
G÷ô÷÷÷÷H–—H÷òáðPPþ÷ðäòô÷HG–òääðPPþFG÷HGHPòPPþGIPPþôðPPÿþððñóþððððððñóþðððððððððð		þððððððððððððññ		þððððððððððððððññññð÷þ
ððððððððððððððððñðññðôôþððððððððððððððððððñððððððôôþððððððððððððððððððððððððððððäðôôþððððððððððððððððððñðððððððääþððððððððððððððððððððððððþ
ððððððððððððððððððððþððððððððððððððððþððððððððððððþððððððððþððððÿþäðó	þääðñóóþððäðáäðññññóþððððäðððññðñññóþððððððððððññðððñññóþ
ððððððððäðäððññðððñðððñóþððððððððäððððððñððððððððððñóþðððððððððððððððñððððððððððððñóþðððððððððððððððððððððððððððþððððððððððäððñððððððððððþ
ððððððððððððððððððððþððððððððððððððððþððððððððððððþððððððððþððððÿþððððþððððððððþððððððððððððþððððððððððððððððþððððððððððððððððððððþ
ððððððððððððððððððððððððþððððððððððððððððððððððððððððþððððððððððððððððððððððððððððððððþððððððððððððððððððððððððððððþððððððððððððððððððððððððþ
ððððððððððððððððððððþððððððððððððððððþððððððððððððþððððððððþððððÿþððððþððððððððþððððððððððððþððððððððððððððððþððððððððððððððððððððþ
ððððððððððððððððððððððððþððððððððððððððððððððððððððððþððððððððððððððððððððððððððððððððþððððððððððððððððððððððððððððþððððððððððððððððððððððððþ
ððððððððððððððððððððþððððððððððððððððþððððððððððððþððððððððþððððÿþððððþððððððððþððððððððððððþððððððððððððððððþððððððððððððððððððððþ
ððððððððððððððððððððððððþððððððððððððððððððððððððððððþððððððððððððððððððððððððððððððððþððððððððððððððððððððððððððððþððððððððððððððððððððððððþ
ððððððððððððððððððððþððððððððððððððððþððððððððððððþððððððððþððððÿþððððþððô÷ôäðþðääô÷÷ðððþððô÷÷÷÷òôäðððþðð÷÷úú÷÷ûô÷òäääððþ
ððôúúûûúúûûúô÷÷òððþððòôúúúûûûNûû÷úúúú÷òððþðððò÷÷ûûNNNNNNûNûúùúùúúúúôðððþðððô÷úNNNNNNNNNûûûû÷ùúúðððþðððòúNNNNNNNNNNNûùùúúôðþ
ððð÷NNNNNNNNNûûúúòäðþðð÷úúûNNNNNûú÷ôäþððôúúúúú÷ôððþððô÷ôòððþððððÿþ	óþ	ññóóþñóóñññþ
óññðððþðñðððþððRDþðððRQàQBþððððñRQQQQQQQ@þ
ððððððñRQQQQQQQRR4þððððððððñRRQQQðóó
3ñðððððððððñRRRRñó	
G4þððððððððRRRR	
ðñó	
–þððððRRRR	

	ññóó	þ
ñðRRRR	


	óñóþñðRRR	



		þñðð	


		þñðð	
		óþñððñÿ
þ_LLL__þLNNNNNNNþLNNNNNNNNþKNNNNNNNNþLJNNNNNNNNþLKNNNNNNNNþI_NNNNNNNNþK_NNNNNNNNþLKNNNNNNNNþILNNNNNNNNþIJNNNNNNNNNþJJLNNNNNNNN_þ	óGILNNNNûûûûûþ	ññóóHHLNûûûûûûûûþñóóñññGHJ_ûûûûûûûûþ
óññðððFHIGúûûûúûþðñðððóGJHúúûúþ
ððRIIJI	úþ	óññóRQàFIJI	þñóñó	ñQQQQQQFHIóó
þððððð		QQQQRQQRððóþðððððóññRRQQQðóó
	óóñðððððððððñRRóó	óñó	

	ðþððððððððRRñ
ñ	

ðñó		
þðððóRR
ñ

	ññóó	þ
ñðRRRó
	óñóþñðRRR
	
ñ	þñððñ

þñðð	
		þñððÿþ	óþIðþññóóþIðþóñññþ
ññðððþ
ðþ
Rþ
RQàQþ		
RQQQQQQQþðð
[RQQQQQQQRR4ó		RRQQQðóó
3



ó[RRRñó	
G4


ó[RR	
ðñó	
–5



	ñ[[R	

	ññóó	

68




	ó[[	


	óñóó	

85






			



		óó	


4K



				


			ñððó


—69				
	ñ	IG
		óóóóó
	óðó—6K	ðððððð
I—IK	ðñððððððññññóó	ó88K

	K964G;K98ñðððððððððððððññ–G8;9HG–H8488		þððððððððððððððñó––––I
			óóþðððððððððððððñóóóñññðñþ
ñðäððððððððððððððñþñðäððððððððððñþñðäðððððñþñðäUäðñþñððñÿñðþðþRIþRQàFIþQQQQQQFHþ
[QQQQRQQRþó	RRQQQðóó
	þ	ó	
ó[Róó	óñó	

	ðñ

ó

ó[_Kñ
ñ	

ðñó		



	
	

	ñûû_
ñ

	ññóó		
	





	

	ó[_ó
	óñóó	
	










		[
	
ñ	óó			


	




			ñ

ññððó			





			
	ñ	IH
		óóóó
	óóóðó

		ðððððð
I—IK	ðóðððóññð	ó	
	88K

	K964G;K98ñðððððððó		ó——GH;9HG–H8488		þðððððððððð—–—ñóó—–––I
			óóþðððððóñððóó	óóñññðñþ
ñðäðñ	óðððñðððñþñðäððððððððððñþñðäðððððñþñðäUäðñþñððñÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
IHRðññóó		
JIþLJIIGðññó	JIIJLþLLHFJIIHGFFFFGHIIJJLLþLLHELLJJIIHHIIJLJJLLLþLLGDLLLLLJIIIJLLJHLLLþLLGDLLLLIòñðòôILJJLLLþLLFDIIJIòðäðäñòIJJILLþLLFDLJHóðððäðñôJILLLþLLEBDGH	òóðDDòðôJJILLþLJEBGCFHEFóóDD	IIHJLL_þ
LIEBGEDBDEDCBDFGGJLLL©þ	¨IFDBDDEFDBABDEHJJJLLL˜_þ˜™IDBDDIGHHGCBDIHGHIJ™§©þ™§DBCDLHJLJIDCFLLIH¨¨§©þ™˜§˜GCILIJLJFCHLNN§©¨¨_þ	¨™¨¨˜GBJFDBAL©¨¨¨§¨_©ôþññòð™§¨¨™©¨¨¨¨§§¨©©__ôôòþòðäðòð™˜§¨¨¨©__¨™÷÷÷ôòPþôðòðñó	——¨¨÷÷÷÷ôðþôðäððñ		——÷÷÷ôòäþ
ôääðð™§÷÷÷òäðþôðääðòòòôòòòðPáþôðäðäðPáþôðáPPáþôðPPÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
IHRðññóó		
JIþLJIIGðññó	JIIJLþLLHFJIIHGFFFFGHIIJJLLþLLHELLJJIIHHIIJLJHLLLþLLGDLLLLLJIIIJLLJJLLLþLLGDLLLLIòñðòôILJJLLLþLLFDIIJIòðäðäñòIJJILLþLLFDLJHóðððäðñôJILLLþLLEBDGH	òóðDDòðôJJILLþLJEBGCFHEFóóDD	IIHJLL_þ
LIEBGEDBDEDCBDFGGJLLL©þ	¨IFDBDDEFDBABDEHJJJLLL˜_þ˜™IDBDDIGHHGCBDIHGHIJ™§©þ™§DBCDLHJLJIDCFLLIH¨¨§©þ™˜§˜GCILIJLJFCHLNN§©¨¨_þ	¨™¨¨˜GBJFDBAL©¨¨¨§¨_©ôþññòð™§¨¨™©¨¨¨¨§§¨©©__ôôòþòðäðòð™˜§¨¨¨©__¨™÷÷÷ôòPþôðòðñó	——¨¨÷÷÷÷ôðþôðäððñ		——÷÷÷ôòäþ
ôääðð™§÷÷÷òäðþôðääðòòòôòòòðPáþôðäðäðPáþôðáPPáþôðPPÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
IHRðññóó		
JIþLJIIGðññó	JIIJLþLLHFJIIHGFFFFGHIIHJLLþLLHELLJJIIHHIIJLJJLLLþLLGDLLLLLJIIIJLLJJLLLþLLGDLLLLIòñðòôILJJLLLþLLFDIIJIòðäðäñòIJJILLþLLFDLJHóðððäðñôJILLLþLLEBDGH	òóðDDòðôJJILLþLJEBGCFHEFóóDD	IIHJLL_þ
LIEBGEDBDEDCBDFGGJLLL©þ	¨IFDBDDEFDBABDEHJJJLLL˜_þ˜™IDBDDIGHHGCBDIHGHIJ™§©þ™§DBCDLHJLJIDCFLLIH¨¨§©þ™˜§˜GCILIJLJFCHLNN§©¨¨_þ	¨™¨¨˜GBJFDBAL©¨¨¨§¨_©ôþññòð™§¨¨™©¨¨¨¨§§¨©©__ôôòþòðäðòð™˜§¨¨¨©__¨™÷÷÷ôòPþôðòðñó	——¨¨÷÷÷÷ôðþôðäððñ		——÷÷÷ôòäþ
ôääðð™§÷÷÷òäðþôðääðòòòôòòòðPáþôðäðäðPáþôðáPPáþôðPPÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
IHRðññóó		
JIþLJIIGðññó	JIIJLþLLHFJIIHGFFFFGHIIJJLLþLLHELLJJIIHHIIJLJJLLLþLLGDLLLLLJIIIJLLJJLLLþLLGDLLLLIòñðòôILJJLLLþLLFDIIJIòðäðäñòIJJILLþLLFDLJHóðððäðñôJILLLþLLEBDGH	òóðDDòðôJJILLþLJEBGCFHEFóóDD	IIHJLL_þ
LIEBGEDBDEDCBDFGGJLLL©þ	¨IFDBDDEFDBABDEHJJJLLL˜_þ˜™IDBDDIGHHGCBDIHGHIJ™§©þ™§DBCDLHJLJIDCFLLIH¨¨§©þ™˜§˜GCILIJLJFCHLNN§©¨¨_þ	¨™¨¨˜GBJFDBAL©¨¨¨§¨_©ôþññòð™§¨¨™©¨¨¨¨§§¨©©__ôôòþòðäðòð™˜§¨¨¨©__¨™÷÷÷ôòPþôðòðñó	——¨¨÷÷÷÷ôðþôðäððñ		——÷÷÷ôòäþ
ôääðð™§÷÷÷òäðþôðääðòòòôòòòðPáþôðäðäðPáþôðáPPáþôðPPÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
IHRðññóó		
JIþLJIIGðññó	JIIJLþLLHFJIIHGFFFFGHIIJJLLþLLHELLJJIIHHIIJLJJLLLþLLGDLLLLLJIIIJLLJJLLLþLLGDLLLLIòñðòôILJJLLLþLLFDIIJIòðäðäñòIJJILLþLLFDLJHóðððäðñôJILLLþLLEBDGH	òóðDDòðôJJILLþLJEBGCFHEFóóDD	IIHJLL_þ
LIEBGEDBDEDCBDFGGJLLL©þ	¨IFDBDDEFDBABDEHJJJLLL˜_þ˜™IDBDDIGHHGCBDIHGHIJ™§©þ™§DBCDLHJLJIDCFLLIH¨¨§©þ™˜§˜GCILIJLJFCHLNN§©¨¨_þ	¨™¨¨˜GBJFDBAL©¨¨¨§¨_©ôþññòð™§¨¨™©¨¨¨¨§§¨©©__ôôòþòðäðòð™˜§¨¨¨©__¨™÷÷÷ôòPþôðòðñó	——¨¨÷÷÷÷ôðþôðäððñ		——÷÷÷ôòäþ
ôääðð™§÷÷÷òäðþôðääðòòòôòòòðPáþôðäðäðPáþôðáPPáþôðPPÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
IHRðññóó		
JIþLJIIGðññó	JIIJLþLLHFJIIHGFFFFGHIIJJLLþLLHELLJJIIHHIIJLJJLLLþLLGDLLLLLJIIIJLLJJLLLþLLGDLLLLIòñðòôILJJLLLþLLFDIIJIòðäðäñòIJJILLþLLFDLJHóðððäðñôJILLLþLLEBDGH	òóðDDòðôJJILLþLJEBGCFHEFóóDD	IIHJLL_þ
LIEBGEDBDEDCBDFGGJLLL©þ	¨IFDBDDEFDBABDEHJJJLLL˜_þ˜™IDBDDIGHHGCBDIHGHIJ™§©þ™§DBCDLHJLJIDCFLLIH¨¨§©þ™˜§˜GCILIJLJFCHLNN§©¨¨_þ	¨™¨¨˜GBJFDBAL©¨¨¨§¨_©ôþññòð™§¨¨™©¨¨¨¨§§¨©©__ôôòþòðäðòð™˜§¨¨¨©__¨™÷÷÷ôòPþôðòðñó	——¨¨÷÷÷÷ôðþôðäððñ		——÷÷÷ôòäþ
ôääðð™§÷÷÷òäðþôðääðòòòôòòòðPáþôðäðäðPáþôðáPPáþôðPPÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
IHRðññóó		
JIþLJIIGðññó	JIIJLþLLHFJIIHGFFFFGHIIJJLLþLLHELLJJIIHHIIJLJJLLLþLLGDLLLLLJIIIJLLJJLLLþLLGDLLLLIòñðòôILJJLLLþLLFDIIJIòðäðäñòIJHILLþLLFDLJHóðððäðñôJILLLþLLEBDGH	òóðDDòðôJJILLþLJEBGCFHEFóóDD	IIHJLL_þ
LIEBGEDBDEDCBDFGGJLLL©þ	¨IFDBDDEFDBABDEHJJJLLL˜_þ˜™IDBDDIGHHGCBDIHGHIJ™§©þ™§DBCDLHJLJIDCFLLIH¨¨§©þ™˜§˜GCILIJLJFCHLNN§©¨¨_þ	¨™¨¨˜GBJFDBAL©¨¨¨§¨_©ôþññòð™§¨¨™©¨¨¨¨§§¨©©__ôôòþòðäðòð™˜§¨¨¨©__¨™÷÷÷ôòPþôðòðñó	——¨¨÷÷÷÷ôðþôðäððñ		——÷÷÷ôòäþ
ôääðð™§÷÷÷òäðþôðääðòòòôòòòðPáþôðäðäðPáþôðáPPáþôðPPÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
IHRðññóó		
JIþLJIIGðññó	JIIJLþLLHFJIIHGFFFFGHIIJJLLþLLHELLJJIIHHIIJLJJLLLþLLGDLLLLLJIIIJLLJJLLLþLLGDLLLLIòñðòôILJHLLLþLLFDIIJIòðäðäñòIJJILLþLLFDLJHóðððäðñôJILLLþLLEBDGH	òóðDDòðôJJILLþLJEBGCFHEFóóDD	IIHJLL_þ
LIEBGEDBDEDCBDFGGJLLL©þ	¨IFDBDDEFDBABDEHJJJLLL˜_þ˜™IDBDDIGHHGCBDIHGHIJ™§©þ™§DBCDLHJLJIDCFLLIH¨¨§©þ™˜§˜GCILIJLJFCHLNN§©¨¨_þ	¨™¨¨˜GBJFDBAL©¨¨¨§¨_©ôþññòð™§¨¨™©¨¨¨¨§§¨©©__ôôòþòðäðòð™˜§¨¨¨©__¨™÷÷÷ôòPþôðòðñó	——¨¨÷÷÷÷ôðþôðäððñ		——÷÷÷ôòäþ
ôääðð™§÷÷÷òäðþôðääðòòòôòòòðPáþôðäðäðPáþôðáPPáþôðPPÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
JIRðññóó		
JLþLIIHGðññó	JIJLNþLHFLJIIHGFFFGHIJJLNLNþNHELJLLJJJJJJJLN_LNKNþNGDLL_NNNNNNNNNN_KNKNþNGDLJ_NNNNNNNNNN_KNKNþNFDLI_N_LLLLL_NN_LNKNþNFDLJKKKKKKKKKKK_LNLNþ_FCJJKKKKKKKKKKKKKLLNþLECIIKKKKKKKKKKKKKKL_þKEBIIKKKKKKKKKKKKKKKLþKEBIGKKKKKKKKHKKKKKKKþLEBGFKKKIKKKKKKKKKKKLþLDBFDKKKKKKKKKKKKJKLLþJDBFDJKKKKKKKKKKKLLLLþ	óGDBGCILKKKKKKKLLLKKKLIðþññóóHEBHCGLLLLLLLLLLLLJHGIðþóñññGECEBELLJJJJJLLLLLLLJ
ñþððFDCD@DHGFDCDFGHHJLLLL
þEDBB@DDCBAAABCDEGHJLL
þ
BB@BAA@@@@@@ABCDHJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4óþ3
ÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
JIRðññóó		
JLþLIIHGðññó	JIJLNþLHFLJIIHGFFFGHIJJLNLNþNHELJLLJJJJJJJLN_LNKNþNGDLL_NNNNNNNNNN_KNKNþNGDLJ_NNNNNNNNNN_KNKNþNFDLI_N_LLLLL_NN_LNKNþNFDLJKKKKKKKKKKK_LNLNþ_FCJJKKKKKKKKKKKKKLLNþLECIIKKKKKKKKKKKKKKL_þKEBIIKKKKKKKKKKKKKKKLþKEBIGKKKIKKKK;KKKKKKKþLEBGFKKKKKK;KKKKKJKKLþLDBFDKKKKLKLKKKKKKKLLþJDBFDJKKK;KKKKKKKLLLLþ	óGDBGCILKKKKKKKLLLKKKLIðþññóóHEBHCGLLLLLLLLLLLLJHGIðþóñññGECEBELLJJFJJLLLLLLLJ
ñþððFDCD@DHGFDDDFGHHJLLLL
þEDBB@DDCBAAABADEGHJLL
þ
BB@BAA@@@@@AABCDHJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4óþ3
ÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
JIRðññóó		
JLþLIIHGðññó	JIJLNþLHFLJIIHGFFFGHIJJLNLNþNHELJLLJJJJJJJLN_LNKNþNGDLL_NNNNNNNNNN_KNKNþNGDLJ_NNNNNNNNNN_KNKNþNFDLI_N_LLLLL_NN_LNKNþNFDLJKKKKKKKKKKK_LNLNþ_FCJJKKKKKKKKKKKKKLLNþLECIIKKKKKKKKKKKKKKL_þKEBIIKKKIKKKKK;KKKKKLþKEBIGKKKKKKKLKLKKJKKKþLEBGFKKKKKKK;KKKKKKKLþLDBFDKKKLKKKLKKKKKKLLþJDBFDJKK;KKKKKKKKLLLLþ	óGDBGCILKKKKKKKLLLKKKLIðþññóóHEBHCGLLLLLLLLLLLLJHGIðþóñññGECEBELLJJFJJLLLLLLLJ
ñþððFDCD@DHGFDDDFBHHJLLLL
þEDBB@DDC@AAABCDEGHJLL
þ
BB@BAA@@@@@AABCDHJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4óþ3
ÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
JIRðññóó		
JLþLIIHGðññó	JIJLNþLHFLJIIHGFFFGHIJJLNLNþNHELJLLJJJJJJJLN_LNKNþNGDLL_NNNNNNNNNN_KNKNþNGDLJ_NNNNNNNNNN_KNKNþNFDLI_N_LLLLL_NN_LNKNþNFDLJKKKKKKKKKKK_LNLNþ_FCJJKKKKKKKKKKKKKLLNþLECIIKKKJKKKKKKKKKKL_þKEBIIKKKKKKKKKKKKJKKLþKEBIGKKKKKKLKKKLKKKKKþLEBGFKKKKKKKKKKKKKKKLþLDBFDKKKKKKKKKKKKKKLLþJDBFDJKKKKKKKKKKKLLLLþ	óGDBGCILKKKKKKKLLLKKKLIðþññóóHEBHCGLLLLHLLLLLLLJHGIðþóñññGECEBELLJJJJJBLLLLLLJ
ñþððFDCD@DHGDDDDFGHHJLLLL
þEDBB@DDCBAAABCDEGHJLL
þ
BB@BAA@@@@@AABCDHJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4óþ3
ÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
JIRðññóó		
JLþLIIHGðññó	JIJLNþLHFLJIIHGFFFGHIJJLNLNþNHELJLLJJJJJJJLN_LNKNþNGDLL_NNNNNNNNNN_KNKNþNGDLJ_NNNNNNNNNN_KNKNþNFDLI_N_LLLLL_NN_LNKNþNFDLJKKKKKKKKKKK_LNLNþ_FCJJKKKKKKKKKKKKKLLNþLECIIKKKKKKKKKKKKJKL_þKEBIIKKKKKKKKKKKKKKKLþKEBIGKKKKKLKKKKKLKKKKþLEBGFKKKKKKKKKKKKKKKLþLDBFDKKKKKKKKKKKKKKLLþJDBFDJKKKKKKKKKKKLLLLþ	óGDBGCILKKKKKKKLLLKKKLIðþññóóHEBHCGLLLLHLLCLLLLJHGIðþóñññGECEBELLEJJJJLLLLLLLJ
ñþððFDCD@DHGFDDDFGHHJJLLL
þEDBB@DDCBAAABCDEGHJLL
þ
BB@BAA@@@@@AABCDHJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4óþ3
ÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
JIRðññóó		
JLþLIIHGðññó	JIJLNþLHFLJIIHGFFFGHIJJLNLNþNHELJLLJJJJJJJLN_LNKNþNGDLL_NNNNNNNNNN_KNKNþNGDLJ_NNNNNNNNNN_KNKNþNFDLI_N_LLLLL_NN_LNKNþNFDLJKKKK;KKKKKK_LNLNþ_FCJJKKLKLKKKKKKKKLLNþLECIIKK;KKKKKKKKKKKL_þKEBIIKKKKKKKKKKKKKKKLþKEBIGKKKKKKKKKKKKKKKKþLEBGFKKKKKKKKKKKKKKKLþLDBFDKKKKKKKKKKKKKKLLþJDBFDJKKKKKKKKKKKLLLLþ	óGDBGCILKKKIKKDLLLKKKLIðþññóóHEBHCGLLGLLLLLLLLLJHGIðþóñññGECEBELLJJJJJLLLLJLLJ
ñþððFDCD@DHGFDDDFGHHJLLLL
þEDBB@DDCBAAABCDEGHJLL
þ
BB@BAA@@@@@AABCDHJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4óþ3
ÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
JIRðññóó		
JLþLIIHGðññó	JIJLNþLHFLJIIHGFFFGHIJJLNLNþNHELJLLJJJJJJJLN_LNKNþNGDLL_NNNNNNNNNN_KNKNþNGDLJ_NNNNNNNNNN_KNKNþNFDLI_N_LLLLL_NN_LNKNþNFDLJKKKKKKKKKKK_LNLNþ_FCJJKLKKKLKKKKKKKLLNþLECIIKKKKKKKKKKKKKKL_þKEBIIKKKKKKKKKKKKKKKLþKEBIGKKKKKKKKKKKKKKKKþLEBGFKKKKKKKKKKKKKKKLþLDBFDKKKKKKKKKKKKKKLLþJDBFDJKKKKKKKDKKKLLLLþ	óGDBGCILKIKIKKKLLLKKKLIðþññóóHEBHCGLLLLLLLLLLLJJHGIðþóñññGECEBELLJJJJJLLLLLLLJ
ñþððFDCD@DHGFDDDFGHHJLLLL
þEDBB@DDCBA@ABCDEGHJLL
þ
BB@BAA@@@@@AABCDHJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4óþ3
ÿþ
		óóó	ñóþ




	óñ	ððñ
þ



÷÷÷÷÷÷	óñ	ðóþ

÷÷÷
	
			

óðóþ

÷÷÷
			


ù	ñ
þ	ðù÷÷÷óñó	

ù÷÷÷	
þ	
ùùññññù÷÷÷÷÷

þ	ñ

			ñ	ù÷÷÷÷÷þ	ñ				
ùùùù÷

þ	LRRùùùùù
		

Lþ
JIRðññóó		
JLþLIIHGðññó	JIJLNþLHFLJIIHGFFFGHIJJLNLNþNHELJLLJJJJJJJLN_LNKNþNGDLL_NNNNNNNNNN_KNKNþNGDLJ_NNNNNNNNNN_KNKNþNFDLI_N_LLLLL_NN_LNKNþNFDLJKKKKKKKKKKK_LNLNþ_FCJJKKKKKKKKKKKKKLLNþLECIIKKKKKKKKKKKKKKL_þKEBIIKKKKKKKKKKKKKKKLþKEBIGKKKKKKKKKKKKKKKKþLEBGFKKKKKKKKKKKKKKKLþLDBFDKKKKKKKKEKKKKKLLþJDBFDJKKIKJKKKKKKLLLLþ	óGDBGCILKKKKKKKLLLJKKLIðþññóóHEBHCGLLLLLLLLLLLLJHGIðþóñññGECEBELLJJJJJLLLLLLLJ
ñþððFDCD@DHGFDDDFGHHJLLLL
þEDBB@DDCBA@ABCDEGHJLL
þ
BB@BAA@@@@@AABCDHJ
þ@A@@@@@@@@@ABC		þA@@@@@@@ABððþR4óþ3
ÿþ
_LLL__þLNNNNNNNNþLNNNNNNNNNNþJKLþKNNNNNNNNNNþJL__LþLJNNNNNNNNNNK__NN_KþLKNNNNNNNNN_N__NNKLþI_NNNNNNNNNNN__N_JLþK_NNNNNNNNN_N___LKLþLKNNNNNNNNN_N__LJLLþILNNNNNNNNNLN_LKLLLþIJNNNNNNNNNNLN_JLLLLþJJLNNNNNNNN_NLNLILLLLþGILNNNNûûûûûûN_HJLLLLLþ
HHLNûûûûûûûûûûLILLLLLJþ
GHJ_ûûûûûûûûûLIKLLLLLJþ	¨FHIGúûûûúûûJKLLLLLLJ_þ˜óGJHúúûúLJLLLLLJ
©þ™§IJI	úúLILLLLJL©þ™˜§˜JI	IKLLHJJ¨¨_ðþ	¨™¨¨IGBJFDBAóNNN¨§¨_©ôððþññòð™§ð™©¨¨¨¨§§¨©©__ôôòððòðäðòð™˜§¨¨¨©__¨™÷÷÷ôòPþôðòðñó	——¨¨÷÷÷÷ôðþôðäððñ		——÷÷÷ôòäþ
ôääðð™§÷÷÷òäðþôðääðòòòôòòòðPáþôðäðäðPáþôðáPPáþôðPPÿþ	IðþIðþþ
ñþþ
þ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþþ
ñþ›þ
«þ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþþ
ñþ›þ
«þ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþþ
ñþ›þ
«þ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþþ
ñþ›þ
«þ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþœœþ
ñþþ
œœþ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþ›þ
ñþ››þ
«þ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþþ
ñþ›þ
«þ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþþúþþúúúþ[úþúúþ
[[úúú	þ
ó	[úú	ðþ	ó	
ó[[[	ððþñ

ó

ó[_K_

	ñóþ
	

	ñûû_KLJKLL	ðñþ
	

	ó[_;LH[
ðñþ



		[K[
ñþ				ðñþñ	IH;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþþ
ñþGJþ
Jþ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþHDHþ
ñþKD@DKþ
HDHþ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþIþ
ñþIFIþ
Iþ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþþ
ñþIJþ
Jþ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþþ
ñþGJþ
Jþ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþþ
ñþIJþ
Jþ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþþ
ñþGJþ
Jþ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþ	IðþIðþþ
ñþIJþ
Jþ
þ
[þ			
[þðð
[[[þó		[[[þ



ó[[[[þ


ó[[[	ñóþ



	ñ[[[	ðñþ


	ó[[	ðñþ



			ðñþ				ðñþñ	IG;	ðñþ—IK	K	ñþ98;
ÿþþ[[[[þ[
[[[[[[[þ[
[[[[[[[þK[
[[[[[[[þK;8[
[[[þ85[
þ		þþ		þ
þð	÷ñþ
W[LLLþùóðñ
¦^]^§^ùùùW[FJJLLLþú÷	ó
§]ù]]úúW[JJJJJILLLLþù÷÷	
¤¦§§§§§úW[HFIJJJJHFL[þù÷ù÷^][<;^W[GJJGHJJJJJ
þù÷ù÷¦[©Z<‰WWGAGJJJIFJJ
[þù÷ù÷¤¦¦¦¦¦
	W
JJJJJJJ
	þù÷ùùùù

	W
JJJJ
W[þ÷[


	W
J
W[þ÷òòô÷÷÷÷÷÷÷[


	WW™þúô÷÷÷÷÷÷÷÷÷
[


	ô÷÷þùûûûûû[
[

ùôòþûúúû[
[ùùùù÷þûùúûú[
þûùûù
ú[þððúúùúþððððùúúùùúúúððððððúùùùùùùúúúIúúþðððð÷ú
óññññññññùúúþððññðððððððððððúþ
ññðððñððñññððùþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[
[[[[[[[þ[
[[[[[[[þ[
[[[[[[[þK;[
[[[þ;85[
þ		þ5þ		þ
þð	÷ñþ
W[LLLþùóðñ
¦^]^§^ùùùW[JFJLLLþú÷	ó
§]ù]]úúW[JJJJJJLLLLþù÷÷	
¤¦§§§§§úW[HFIJJJJIHL[þù÷ù÷^][<;^W[JGJGHJJJJJ
þù÷ù÷¦[©Z<‰WWJH@GJJIFJJ
[þù÷ù÷¤¦¦¦¦¦
	W
JJJJJJJ
	þù÷ùùùù

	W
JJJJ
W[þ÷[


	W
J
W[þ÷òòô÷÷÷÷÷÷÷[


	WW™þúô÷÷÷÷÷÷÷÷÷
[


	ô÷÷þùûûûûû[
[

ùôòþûúúû[
[ùùùù÷þûùúûú[
þûùûù
ú[þððúúùúþððððùúúùùúúúððððððúùùùùùùúúúIúúþðððð÷ú
óññññññññùúúþððññðððððððððððúþ
ññðððñððñññððùþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[
[[[[[[[þ[
[[[[[[[þ[
[[[[[[[þK[
[[[þK;8[
þ		þ85þ		þ
þð	÷ñþ
W[LLLþùóðñ
¦^]^§^ùùùW[JHFLLLþú÷	ó
§]ù]]úúW[JJJJJJLLLLþù÷÷	
¤¦§§§§§úW[HFIJJJJJIL[þù÷ù÷^][<;^W[JJHGHJJJJJ
þù÷ù÷¦[©Z<‰WWJHFDHJIFJJ
[þù÷ù÷¤¦¦¦¦¦
	W
JHJJJJJ
	þù÷ùùùù

	W
JJJJ
W[þ÷[


	W
J
W[þ÷òòô÷÷÷÷÷÷÷[


	WW™þúô÷÷÷÷÷÷÷÷÷
[


	ô÷÷þùûûûûû[
[

ùôòþûúúû[
[ùùùù÷þûùúûú[
þûùûù
ú[þððúúùúþððððùúúùùúúúððððððúùùùùùùúúúIúúþðððð÷ú
óññññññññùúúþððññðððððððððððúþ
ññðððñððñññððùþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[
[[[[[[[þ[
[[[[[[[þ[
[[[[[[[þ[
[[[þK;[
þ		þ;8þ		þ
þð	÷ñþ
W[LJFþùóðñ
¦^]^§^ùùùW[JIHLLLþú÷	ó
§]ù]]úúW[JJJJJJLLLLþù÷÷	
¤¦§§§§§úW[IHIJJJJJJL[þù÷ù÷^][<;^W[JJJHIJJJJJ
þù÷ù÷¦[©Z<‰WWJHFIJJIGJJ
[þù÷ù÷¤¦¦¦¦¦
	W
E@EJJJJ
	þù÷ùùùù

	W
HJJJ
W[þ÷[


	W
J
W[þ÷òòô÷÷÷÷÷÷÷[


	WW™þúô÷÷÷÷÷÷÷÷÷
[


	ô÷÷þùûûûûû[
[

ùôòþûúúû[
[ùùùù÷þûùúûú[
þûùûù
ú[þððúúùúþððððùúúùùúúú›ððððððúùùùùùùúúúIúúþðððð÷ú
óññññññññùúúþððññðððððððððððúþ
ññðððñððñññððùþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[
[[[[[[[þ[
[[[[[[[þ5[
[[[[[[[þ[
[[[þK[
þ		þK;þ		þ
þð	÷ñþ
W[LLHþùóðñ
¦^]^§^ùùùW[JIHILLþú÷	ó
§]ù]]úúW[JJJFJJLLLLþù÷÷	
¤¦§§§§§úW[JIJJJJJJJL[þù÷ù÷^][<;^W[JJJIJJJJJJ
þù÷ù÷¦[©Z<‰WWJHFIJJJIJJ
[þù÷ù÷¤¦¦¦¦¦
	W
JGDJJJJ
	þù÷ùùùù

	W
JJJJ
W[þ÷[


	W
J
W[þ÷òòô÷÷÷÷÷÷÷[


	WW™þúô÷÷÷÷÷÷÷÷÷
[


	ô÷÷þùûûûûû[
[

ùôòþûúúû[
[ùùùù÷þûùúûú[
þûùûù
ú[þððúúùúþððððùúúùùúúú›ððððððúùùùùùùúúúIúúþðððð÷ú
óññññññññùúúþððññðððððððððððúþ
ññðððñððñññððùþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[
[[[[[[[þ[
[[[[[[[þ85[
[[[[[[[þ5[
[[[þ[
þ		þKþ		þ
þð	÷ñþ
W[LLLþùóðñ
¦^]^§^ùùùW[JJILLLþú÷	ó
§]ù]]úúW[JJJHFJLLLLþù÷÷	
¤¦§§§§§úW[JJJJJJJJJL[þù÷ù÷^][<;^W[JJJJJJJJJJ
þù÷ù÷¦[©Z<‰WWJHFIJJJJJJ
[þù÷ù÷¤¦¦¦¦¦
	W
JGHHJJJ
	þù÷ùùùù

	W
HCHJ
W[þ÷[


	W
J
W[þ÷òòô÷÷÷÷÷÷÷[


	WW™þúô÷÷÷÷÷÷÷÷÷
[


	ô÷÷þùûûûûû[
[

ùôòþûúúû[
[ùùùù÷þûùúûú[
þûùûù
ú[þððúúùúþððððùúúùùúúú›ððððððúùùùùùùúúúIúúþðððð÷ú
óññññññññùúúþððññðððððððððððúþ
ññðððñððñññððùþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[
[[[[[[[þ[
[[[[[[[þ;8[
[[[[[[[þ85[
[[[þ[
þ		þþ		þ
þð	÷ñþ
W[LLLþùóðñ
¦^]^§^ùùùW[JJILLLþú÷	ó
§]ù]]úúW[JJJJHFLLLLþù÷÷	
¤¦§§§§§úW[JJJJJJJJJL[þù÷ù÷^][<;^W[HFIJJJJJJJ
þù÷ù÷¦[©Z<‰WWH@BGHJJJJJ
[þù÷ù÷¤¦¦¦¦¦
	W
HCEIFJJ
	þù÷ùùùù

	W
HGEH
W[þ÷[


	W
J
W[þ÷òòô÷÷÷÷÷÷÷[


	WW™þúô÷÷÷÷÷÷÷÷÷
[


	ô÷÷þùûûûûû[
[

ùôòþûúúû[
[ùùùù÷þûùúûú[
þûùûù
ú[þððúúùúþððððùúúùùúúú›ððððððúùùùùùùúúúIúúþðððð÷ú
óññññññññùúúþððññðððððððððððúþ
ññðððñððñññððùþððððððððððððþðððððððððð
þððððððððþððððÿþþ[[[[þ[
[[[[[[[þ[
[[[[[[[þK;[
[[[[[[[þ;85[
[[[þ5[
þ		þþ		þ
þð	÷ñþ
W[LLLþùóðñ
¦^]^§^ùùùW[JJJLLLþú÷	ó
§]ù]]úúW[JJJJIHLLLLþù÷÷	
¤¦§§§§§úW[HFIJJJIFJL[þù÷ù÷^][<;^W[JJJGHJJJJJ
þù÷ù÷¦[©Z<‰WWJDDIJJIFJJ
[þù÷ù÷¤¦¦¦¦¦
	W
JFGJJJJ
	þù÷ùùùù

	W
JHHJ
W[þ÷[


	W
J
W[þ÷òòô÷÷÷÷÷÷÷[


	WW™þúô÷÷÷÷÷÷÷÷÷
[


	ô÷÷þùûûûûû[
[

ùôòþûúúû[
[ùùùù÷þûùúûú[
þûùûù
ú[þððúúùúþððððùúúùùúúú›ððððððúùùùùùùúúúIúúþðððð÷ú
óññññññññùúúþððññðððððððððððúþ
ññðððñððñññððùþððððððððððððþðððððððððð
þððððððððþððððÿþ[
[
þ[


[[WTþ[	
[[[[WUUþW
[[[
	WUUUUþ
V[[
	WWWWWUUUþ

W[
WWWWV	WäWUUðþW
	WW	VWWWWäääðWðððþ
W
	òWW
VWWñððóòòäòäòðþ
W

ðUV
	óUWääðóôòääðòððþððäUU
[òóVUððòôòððððòòþððääWWñòóñWUVäððòóWUWääóòòðþðððUVWñðòWUU	òððò	óòUUW
óñððþðððñóññóóWW	ñUW
	óòóððððþ
ðððñäòðWWñðñððôäòWóðþððððWVWóññððððððþððððððððððððþððððððððþððððÿþþþþþþþþþþþþ[þJùùþIùùùùþ¨Hùùùþ˜™Hþ÷§˜¨þð÷§™þôðG˜úþ÷òI˜©úùþHô˜©ùúúþ—÷™¨ùúúúþ—÷¨§úúúúþIHú§úúúúþùúGJû¨©úúúþ

ùúúúHG_¨úúú§þùúúú÷HH©©úú©™÷þ
ù
úúú÷—H_¨©ú¨˜ô÷þñ	ùúúôú—GI¨§˜H÷ôóþððñññ	ù
úúôúI——GHô÷ò	þðððññññññ	ùú÷ô÷ùù÷ôò
óððþðñððñññññ	úôô÷÷÷ôòò
óðþððððñññññ	
		òò÷ôòòò
	ðþ
ððððññññññññó						óþðððñðññðððððððððþðððñððððððððþððððððððþððððÿþ[
W	þ[WWþ		Wþ[	Wþ		þ[	þ
þ
þ[[þùúúþùù÷ùþHùù÷þò–ù÷÷ùþðòHùô÷þððòôG—úûþðð———I—HúþðððóIG—H
ùþðððððñ——H
ôûûþððððóñññòò÷ûþððððððòò÷ûúþðððððòûþðððòù÷òþððôñññþòðððþððÿþWVUUVWþVUUUUUUUUVþVUUUUUUUUUUVþSUUUUUUUUUUVþVRSUUUUUUUV	þWURRSTTUW
þW					þô÷þääðð÷ôô÷þäô÷äôù÷ôþäò	ó	äô	ó	ôþäð

ð÷

ôòþóäðòôô÷÷ôòò	þó	òðäääðò	óóþó÷ôôòòôôðóþòðóó		óóôþä	þóÿþWW
þUL[	
þ
[[þULJJ[	
þKKKKKKþULDJJF[W
þ_;KKKKKK_þULDJJFJJ[W	þ
_8KKKK98_ULJJJJFHEJ[WWþ_KKKKKKK_VKJJJJJFJJJJWþKKKKKK_VKJJJJJHFHEJWþ[WKJJJJJJFJJJWþVLJJJJJJIFIHWþ÷÷÷WKJJJJJJJFJJWþùùùùùùùúúûWKJJJJJJJFIHWþùùùùùWKJJJJJJFJJJWþù÷ùùù÷ùWKJJJJJJFIEJ	þ÷÷÷÷÷ùùùûWKJJJJJFJJJJWþùùùùùüWKJJJJFIJJJJ	þûüüüNNNNNNûWKJJJHHJJJJJ	þûûûûûûûûûûúWJJJHFJJJJJJ	þúWJJJJFJJBJKJ	þúûûúûûúûûúúWJIIIFJJJJJJ	þûûúûûúúWEDDDGJJGJBJ	þ÷ûú÷ûúùû	WWVWGDCDGGJJJ	þ÷û÷ûûWUUWWWVWGECDGJJ	þ÷÷òú÷ò	UUUUUWWWVWGFDFI	þññññññ	UUUUUUUUWWWVVGEF	
ñþñðñññðWUUUUUUUUVTWWWVVW		W[ñþñððññðññWUUUUUVSUVTWWWW		

[ñðþððððððññññWUUWSUVSUVTW	




[óððþððððñðððññWWTWSUVSUW



[óñðþðððððððððñWWTWSUW


[óñðþ
ðððððððñðñWWTW

[óñðþððððððñðññW
[óñðþðððððñððñóñðþððððððñðþððððÿþWW
þUL[	
þ
[[þULJJ[	
þKKKKKKþULEDJJ[W
þ_;KKKKKK_þULEDJJJF[W	þ
_98KKKK9_ULJJJJJHFH[WWþ_KKKKKKK_VKJJJJJJFJJJWþKKKKKK_VKJJJJJJIFIHWþ[WKJJJJJJJFJJWþVLJJJJJJJFIHWþ÷÷÷WKJJJJJJFJJJWþùùùùùùùúúûWKJJJJJJFIEJWþùùùùùWKJJJJJFJJJJWþù÷ùùù÷ùWKJJJJFIJJJJ	þ÷÷÷÷÷ùùùûWKJJJHHJJJJJWþùùùùùüWKJJHFJJJJJJ	þûüüüNNNNNNûWKJJJFJJJJJJ	þûûûûûûûûûûúWJJGIHJJJJHJ	þúWJJJFJJJGHBH	þúûûúûûúûûúúWJJJFJJJJJHJ	þûûúûûúúWGEEFIJJKJGJ	þ÷ûú÷ûúùû	WWVWIFDFIIJJJ	þ÷û÷ûûWUUWWWVWIGDFIJJ	þ÷÷òú÷ò	UUUUUWWWVWIHFHJ	þññññññ	UUUUUUUUWWWVVIGH	
ñþñðñññðWUUUUUUUUVTWWWVVW		W[ñþñððññðññWUUUUUVSUVTWWWW		

[ñðþððððððññññWUUWSUVSUVTW	




[óððþððððñðððññWWTWSUVSUW



[óñðþðððððððððñWWTWSUW


[óñðþ
ðððððððñðñWWTW

[óñðþððððððñðññW
[óñðþðððððñððñóñðþððððððñðþððððÿþWW
þUL[	
þ
[[þULJJ[	
þKK8KKKþULHEJJ[W
þ_;;KKKKK_þULHEDJJJ[W	þ
_K9KKKKK_ULJJDJJJJF[WWþ_KKKKKKK_VKJJJJJJJFIHWþKKKKKK_VKJJJJJJFJJJWþ[WKJJJJJJFIEJWþVLJJJJJFJJJJWþ÷÷÷WKJJJJFIJJJJWþùùùùùùùúúûWKJJJHHJJJJJWþùùùùùWKJJHFJJJJJJWþù÷ùùù÷ùWKJJJFJJJJJJ	þ÷÷÷÷÷ùùùûWKJGIHJJJJJJWþùùùùùüWKJJFJJJJJJJ	þûüüüNNNNNNûWKFHFJJJJJJJ	þûûûûûûûûûûúWJJJFJJJJJIJ	þúWJJFIFJJBIGI	þúûûúûûúûûúúWJJJJFFJJJIJ	þûûúûûúúWGEEFIJJKJBJ	þ÷ûú÷ûúùû	WWVWIFDFIIJJJ	þ÷û÷ûûWUUWWWVWIGDFIJJ	þ÷÷òú÷ò	UUUUUWWWVWIHFHJ	þññññññ	UUUUUUUUWWWVVIGH	
ñþñðñññðWUUUUUUUUVTWWWVVW		W[ñþñððññðññWUUUUUVSUVTWWWW		

[ñðþððððððññññWUUWSUVSUVTW	




[óððþððððñðððññWWTWSUVSUW



[óñðþðððððððððñWWTWSUW


[óñðþ
ðððððððñðñWWTW

[óñðþððððððñðññW
[óñðþðððððñððñóñðþððððððñðþððððÿþWW
þUL[	
þ
[[þULJJ[	
þKKKKKKþULJHJJ[W
þ_;K;KKKK_þULJHEDJJ[W	þ
_KK9KKKK_ULJJEDJJFJ[WWþ_KK8KKKK_VKJJJJJJFIEJWþKKKKKK_VKJJJJJFJJJJWþ[WKJJJJFIJJJJWþVLJJJHHJJJJJWþ÷÷÷WKJJHFJJJJJJWþùùùùùùùúúûWKJJJFJJJJJJWþùùùùùWKJGIHJJJJJJWþù÷ùùù÷ùWKJJFJJJJJJJ	þ÷÷÷÷÷ùùùûWKFHFJJJJJJJWþùùùùùüWKJJFJJJJJJJ	þûüüüNNNNNNûWKJFIFJJJJJJ	þûûûûûûûûûûúWJJJJFFJJJJJ	þúWJJJJFJJGJBJ	þúûûúûûúûûúúWJJJJJFJJJJJ	þûûúûûúúWHFFGJJJKJGJ	þ÷ûú÷ûúùû	WWVWJGEGJJJJJ	þ÷û÷ûûWUUWWWVWJHEGJJJ	þ÷÷òú÷ò	UUUUUWWWVWJIGIJ	þññññññ	UUUUUUUUWWWVVJHI	
ñþñðñññðWUUUUUUUUVTWWWVVW		W[ñþñððññðññWUUUUUVSUVTWWWW		

[ñðþððððððññññWUUWSUVSUVTW	




[óððþððððñðððññWWTWSUVSUW



[óñðþðððððððððñWWTWSUW


[óñðþ
ðððððððñðñWWTW

[óñðþððððððñðññW
[óñðþðððððñððñóñðþððððððñðþððððÿþWW
þUL[	
þ
[[þULJJ[	
þKKKKKKþULJJJJ[W
þ_;KKKKKK_þULJJHEHF[W	þ
_KK;8KKK_ULJJHEDIJJ[WWþ_KK9KKKK_VKJJJHDJJJJJWþKKKKKK_VKJJHFJJJJJJWþ[WKJJJFJJJJJJWþVLJGIHJJJJJJWþ÷÷÷WKJJFJJJJJJJWþùùùùùùùúúûWKFHFJJJJJJJWþùùùùùWKJJFJJJJJJJWþù÷ùùù÷ùWKJFIFJJJJJJ	þ÷÷÷÷÷ùùùûWKJJJFFJJJJJWþùùùùùüWKJJJFJJJJJJ	þûüüüNNNNNNûWKJJJJFHEJJJ	þûûûûûûûûûûúWJJJJJJJJJJJ	þúWJJJJJJJKJGJ	þúûûúûûúûûúúWJJJJJJJJJJJ	þûûúûûúúWGEEFIJJBJDJ	þ÷ûú÷ûúùû	WWVWIFDFIIJJJ	þ÷û÷ûûWUUWWWVWIGDFIJJ	þ÷÷òú÷ò	UUUUUWWWVWIHFHJ	þññññññ	UUUUUUUUWWWVVIGH	
ñþñðñññðWUUUUUUUUVTWWWVVW		W[ñþñððññðññWUUUUUVSUVTWWWW		

[ñðþððððððññññWUUWSUVSUVTW	




[óððþððððñðððññWWTWSUVSUW



[óñðþðððððððððñWWTWSUW


[óñðþ
ðððððððñðñWWTW

[óñðþððððððñðññW
[óñðþðððððñððñóñðþððððððñðþððððÿþWW
þUL[	
þ
[[þULJJ[	
þKKKKKKþULJJJJ[W
þ_;KKKKKK_þULJJJHHJ[W	þ
_KKK98KK_ULJJHFEDJJ[WWþ_KKKKKKK_VKJJJFEDJJJJWþKKKKKK_VKJGIHJJJJJJWþ[WKJJFJJJJJJJWþVLFHFJJJJJJJWþ÷÷÷WKJJFJJJJJJJWþùùùùùùùúúûWKJFIFJJJJJJWþùùùùùWKJJJFFJJJJJWþù÷ùùù÷ùWKJJJFJJJJJJ	þ÷÷÷÷÷ùùùûWKJJJJFHEJJJWþùùùùùüWKJJJJJFJJJJ	þûüüüNNNNNNûWKJJJJJHFHEJ	þûûûûûûûûûûúWJJJJJJJJJJJ	þúWJJJJJJJBJKJ	þúûûúûûúûûúúWJJJJJJJJJJJ	þûûúûûúúWFDDEHJJKJHJ	þ÷ûú÷ûúùû	WWVWHEDEHHJJJ	þ÷û÷ûûWUUWWWVWHFDEHJJ	þ÷÷òú÷ò	UUUUUWWWVWHGEGJ	þññññññ	UUUUUUUUWWWVVHFG	
ñþñðñññðWUUUUUUUUVTWWWVVW		W[ñþñððññðññWUUUUUVSUVTWWWW		

[ñðþððððððññññWUUWSUVSUVTW	




[óððþððððñðððññWWTWSUVSUW



[óñðþðððððððððñWWTWSUW


[óñðþ
ðððððððñðñWWTW

[óñðþððððððñðññW
[óñðþðððððñððñóñðþððððððñðþððððÿþWW
þUL[	
þ
[[þULJJ[	
þKKKKKKþULJJJF[W
þ_;KKK;8K_þULJGIHJJ[W	þ
_KKKK9;K_ULJJFJJFJJ[WWþ_KKKKKKK_VKFHFJJFJJJJWþKKKKKK_VKJJFJJJJJJJWþ[WKJFIFJJJJJJWþVLJJJFFJJJJJWþ÷÷÷WKJJJFJJJJJJWþùùùùùùùúúûWKJJJJFHEJJJWþùùùùùWKJJJJJFJJJJWþù÷ùùù÷ùWKJJJJJHFHEJ	þ÷÷÷÷÷ùùùûWKJJJJJJFJJJWþùùùùùüWKJJJJJJIFIH	þûüüüNNNNNNûWKJJJJJJJFJJ	þûûûûûûûûûûúWJJJJJJJJJJJ	þúWJJJJJJJGJHJ	þúûûúûûúûûúúWJJJJJJJJJJJ	þûûúûûúúWEDDDGJJJJBJ	þ÷ûú÷ûúùû	WWVWGDCDGGJJJ	þ÷û÷ûûWUUWWWVWGECDGJJ	þ÷÷òú÷ò	UUUUUWWWVWGFDFI	þññññññ	UUUUUUUUWWWVVGEF	
ñþñðñññðWUUUUUUUUVTWWWVVW		W[ñþñððññðññWUUUUUVSUVTWWWW		

[ñðþððððððññññWUUWSUVSUVTW	




[óððþððððñðððññWWTWSUVSUW



[óñðþðððððððððñWWTWSUW


[óñðþ
ðððððððñðñWWTW

[óñðþððððððñðññW
[óñðþðððððñððñóñðþððððððñðþððððÿþWW
þUL[	
þ
[[þULJG[	
þKKKKKKþULJJFJ[W
þ_;KKK;9K_þULFHFJJJ[W	þ
_KKKKK8K_ULJJFJJJJJ[WWþ_KKKKKKK_VKJFIFJJJJJJWþKKKKKK_VKJJJFFJJJJJWþ[WKJJJFJJJJJJWþVLJJJJFHEJJJWþ÷÷÷WKJJJJJFJJJJWþùùùùùùùúúûWKJJJJJHFHEJWþùùùùùWKJJJJJJFJJJWþù÷ùùù÷ùWKJJJJJJIFIH	þ÷÷÷÷÷ùùùûWKJJJJJJJFJJWþùùùùùüWKJJJJJJJFIH	þûüüüNNNNNNûWKJJJJJJFJJJ	þûûûûûûûûûûúWJJJJJJHJJJJ	þúWJJJJJHJKJGJ	þúûûúûûúûûúúWIIIJJFJJJJJ	þûûúûûúúWDCCDFIJBJGJ	þ÷ûú÷ûúùû	WWVWFDBDFFJJJ	þ÷û÷ûûWUUWWWVWFDBDFII	þ÷÷òú÷ò	UUUUUWWWVWFEDEH	þññññññ	UUUUUUUUWWWVVFDE	
ñþñðñññðWUUUUUUUUVTWWWVVW		W[ñþñððññðññWUUUUUVSUVTWWWW		

[ñðþððððððññññWUUWSUVSUVTW	




[óððþððððñðððññWWTWSUVSUW



[óñðþðððððððððñWWTWSUW


[óñðþ
ðððððððñðñWWTW

[óñðþððððððñðññW
[óñðþðððððñððñóñðþððððððñðþððððÿþ

þó			
þñ	
				
þð

				þñ	


	
ñþññþñ	




ñðóñþñðñ







ðóóóñþðWVñWUUW


	
Góóóóóþ
ðððVV	UUUWW	

H–	GóóóóóðþðððññðððVUWW	
		

–ññóðððþððððóñññUWññV	–UU


ð	óóððððþðððððððð—VU

	VUWñ	ñðððóðððþððððð–Wññóñññðññóóððððþ
ððððððòðVWññððñññðððþðððñðððððñðððñðþðððððððññðððþððððððóþððððÿþ444þ444688þ55Ô4Ô68ˆˆþ555Ô4Ô88ˆ888þ55554588ˆˆ88ˆˆþ5555Ô4Ô888ˆ8ˆˆ555þ555555456668ˆˆˆ65555þ555555ÔÔÔ656ˆˆˆ65Ô554ÔÔþ5555Ô55456558ˆˆ854Ô5Ô4ÔÔ44þ44Ô5ÔÔÔÔÔ4ÔÔÔÔ8ˆ8Ô44554ÔÔÔ4Ô55ÔÔ54ÔÔ66ÔÔÔ5Ô5568ˆ854Ô5Ô455Ô4Ô5ô4Ô5Ô68866Ô4Ô6568ˆ86ÔÔ55455554Ôôô4ÔÔ8ˆˆˆ86ÔÔ688ˆˆˆ8Ô55545555Ôôôôôòò68ˆˆˆ86Ô588ˆˆ8ˆ866ÔÔ55ÔÔ5ôôôôôòòò88ˆˆ6Ô468ˆ888ˆˆ86ÔÔÔÔÔ5ôôôôôôþòòò8665Ô8ˆ888ˆˆ8854ÔÔÔÔôôôôôþòò6ÔÔ58ˆˆ8ˆˆ8854ÔÔ6ôôôôôþ
òò4Ô8ˆˆˆˆˆ654Ô66ôôôôþòÔ588885Ô5Ô66ôôôþò45445Ô68ôôôþò888ˆôôôþòˆôôÿþ444þ555455þ5555458ˆˆþÔÔ5554Ô8ˆ88þ55ÔÔÔÔÔÔ88ˆ8888þÔÔ55Ô6ÔÔÔ58ˆˆˆ8866þÔÔÔ56666Ô4Ô88ˆˆ8ˆ6555þ88ÔÔÔ568886Ô4688ˆˆ86555555þ8888ÔÔÔ8ˆˆˆ88ÔÔ888886555Ô5555ÔÔþ8886Ô56ˆˆˆˆˆ85588886Ô555ÔÔ555ÔÔ5ò8654Ô8ˆˆˆˆˆ85588888ÔÔ5ÔÔÔÔÔÔÔôôòòÔ54568ˆˆˆˆ85588ˆ88ÔÔ5666666ôôôòòòò45Ô6888865Ô688654Ô68ˆ88ôôôôôþòòòÔ5Ô66666545554568ˆˆˆ8ôôôôþòòò5ÔÔ6ÔÔÔ5555Ô6ˆˆˆˆôôôôþ
òò5ÔÔÔ6666688ˆˆˆˆôôôþòò455Ô6688888ôôôþòòòÔ44Ô5ôôôôþòòòòôôôôþòòôôÿþ5566þÔÔ5688þ55ÔÔÔ688866þ8855ÔÔ88ˆ88655þ888ˆ88556ˆˆˆˆˆ865566þ	ˆˆˆ888ˆ85568ˆˆˆˆˆˆ6556555þˆˆˆ8ˆˆ854Ô88888ˆˆˆ65ÔÔ558ˆ88þòˆˆˆˆ8ÔÔ5ÔÔ66668ˆˆ8Ô444Ô8ˆ888888òòˆ88Ô5455555ÔÔ68ˆ86ÔÔÔˆˆˆˆ8888ˆòòòò55444ÔÔÔÔÔ5Ô688668ˆˆˆˆˆ88ôôôòòòòòò44444Ô44455ÔÔ66888ˆ888ôôôôþòòòòòò55Ô555544Ô5ÔÔÔ6Ô6ôôôôôþòòòòòò66666ÔÔ5Ô4445ôôôôôþ
òòòòòòòÔ6ÔÔÔôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ44Ô66þˆˆ65Ô4Ô6Ô55þ668ˆˆˆ8ˆ65Ô5ÔÔÔ54ˆˆþ4ÔÔ68ˆˆˆ8854Ô555444Ôˆ44þ	4ÔÔ8ˆˆ886ÔÔ444ÔÔ5555ˆ455ÔÔþòÔÔ8888Ô5ÔÔÔÔ5555555ˆ455Ô5ÔˆˆÔþòòò555Ô44445555ÔÔÔ55Ô4Ô555ÔÔˆˆˆÔòòòòò55Ô4Ô55Ô6Ô66ÔÔ55Ô44Ô5555Ôˆˆòòòòòòòò556Ô6668666Ô55ÔÔ44Ô5ôôôôòòòòòòòòòòòÔÔÔÔ6ÔÔÔ5555ôôôôôôôôôþòòòòòòòòòòòò4444ôôôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþÔÔÔ555þ44Ô555ÔÔ55ÔÔÔþ666ÔÔ4Ô5555555ÔÔÔÔÔÔþ
ˆˆ866ÔÔÔÔ55Ô5555ÔÔÔÔÔ6ÔÔÔÔþˆˆ8865Ô444Ô44Ô55ÔÔÔÔ66ÔÔÔÔ6ÔÔþˆˆˆˆ6ÔÔÔÔÔÔÔ4Ô55ÔÔ6ÔÔÔ55ÔÔ6Ô555þòòˆˆˆˆˆˆ8654Ô55ÔÔÔÔ55555Ô6ÔÔ55ÔÔòòòòòˆˆˆ8Ô54455555Ô44Ô55Ô55555ôÔòòòòòòòò8866Ô555ÔÔÔÔ5Ô4Ôôôôôôôôôòòòòòòòòòòòˆˆˆˆˆˆ86Ôôôôôôôôôôôôôòòòòòòòòòòòòò8ˆ886ôôôôôôôôôôôôôôþòòòòòòòòòòòòòòôôôôôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþÔÔÔ55þÔÔÔ5ÔÔ5555ÔÔþ8888ÔÔ5Ô4Ô555Ô5555þ88ˆ88866ÔÔ554Ô55555ÔÔÔþ6688ˆˆˆ866686Ô544Ô5ÔÔÔÔ588þÔÔ68ˆˆˆ8668ˆˆ86Ô5Ô4Ô4Ô4Ô58ˆˆˆþ55Ô66886ÔÔ6ˆˆˆˆ6ÔÔÔÔÔÔÔÔ568ˆˆ88þ5555Ô55Ô55Ô8ˆˆˆ8888888ÔÔ568ˆ8855ò44444ÔÔ44568ˆˆˆˆˆˆˆˆ65ÔÔ888ôôôôòòòò5555545Ô688ˆˆˆˆ8ÔÔÔ5Ôôôôôôôôòòòòòòò55Ô4Ô55ÔÔÔÔÔÔ4Ôôôôôôôôôôôòòòòòòòòòò55ÔÔ4444ÔÔôôôôôôôôôôôôòòòòòòòòòòòò6ÔÔÔ555ôôôôôôôôôôôôôþòòòòòòòòòòò8886ôôôôôôôôôôôôôþòòòòòòòòòòò8ôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ888þ88ˆˆ8ˆ88ˆþ88ˆ8ˆˆˆˆ888865þ888ˆˆ86668866545Ôþ6688ˆ86555Ô8ˆˆˆ888666þ
ÔÔ6886Ô4554Ô8ˆˆˆˆˆ886ÔÔþ555Ô66ÔÔ566ÔÔ56ˆˆˆˆˆˆ8ÔÔ555þÔÔ555Ô54Ô66665568ˆˆˆˆ86Ô58ˆˆˆþ44ÔÔ444Ô6555ÔÔ5ÔÔ88ˆ886546ˆˆˆ654Ô44ÔÔÔ5654445Ô5456666Ô54Ô8ˆˆ8ôô4ÔÔ55556Ô45545Ô54Ô55554ÔÔ888ôôôô4Ô55556Ô45545ÔÔ55444445Ô88ôôôôôôòòòòÔÔÔ544Ô5Ô66Ô55Ô55566ôôôôôôôôòòòòòò55Ô5Ô88866ÔÔ5ÔÔ66ôôôôôôôôôòòòòòòòò6888888866666ôôôôôôôôôôôþòòòòòòòò8ˆˆ8888886ôôôôôôôôôôþòòòòòòòˆˆ888886ôôôôôôôôôþ
òòòòòòò8886ôôôôôôôôôþòòòòòòÔ5ôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþˆÔÔþ66ÔÔÔÔþ8866ÔÔÔˆ88þ66865Ô68ˆ88ÔÔþ566665Ô88ˆˆˆ8Ô455þÔÔ66Ô556ˆˆˆˆ88545ÔˆþÔÔÔÔÔ55688ˆˆˆ8654ÔˆˆˆÔþ	55ÔÔ55Ô6ÔÔ88888ÔÔÔˆˆˆÔ44þÔÔ5555ÔÔÔ5Ô56Ô6Ô6Ô45ÔˆÔÔ4Ô66þ44Ô5ÔÔ4ÔÔ5Ô455555Ô54555545Ô666þ444Ô444Ô5ÔÔÔ4555Ô5554Ô5Ô4Ô5Ô66ôÔÔ444444564Ô5Ô555Ô55544Ô4Ô5ÔÔôôô5ÔÔÔÔÔÔÔ5555ÔÔ6555Ô55444Ô55Ôôôôô55ÔÔ55ÔÔÔÔ45688ÔÔÔÔ5ÔÔ4Ô55ôôôôôôòòò66Ô45ÔÔÔ8ˆˆ8866Ô5ÔÔÔ55ôôôôôôôòòòòò5Ô688ˆˆˆˆˆ886Ô55Ô55ôôôôôôôôþòòòòò88ˆˆˆˆˆˆ886Ô555ôôôôôôôôþòòòòˆˆˆˆˆˆˆ886Ô55ôôôôôôôþ
òòòòˆˆˆˆˆ886Ô5ôôôôôôþòòòˆˆˆ888Ô5ôôôôôþòòò888Ôôôôôôþòò66ôôôôþòòôôÿþ8þ55688þÔÔ444Ô556888þÔÔ5ÔÔÔ444Ô5566888þ8ÔÔ5ÔÔ5Ô444Ô55Ô6665Ôþ8Ô45Ô6ÔÔ5ÔÔ4455ÔÔÔ554þòÔÔ5666ÔÔ55Ô4Ô55555Ô4Ô5þ	òò4Ô68666Ô5Ô4Ô55555Ô44Ô5þòòòò88866Ô5ÔÔ555555ÔÔÔÔ5Ô4þòòòòòˆ886Ô5455ÔÔ55ÔÔ555ÔÔÔÔ55þòòòòòòò88654Ô5Ô5Ô444Ô555Ô5ÔÔÔ555òòòòòòòò86Ô544Ô5554Ô555ÔÔÔôôôôôôòòòòòòòòòò666886545ÔÔôôôôôôôôôôôþòòòòòòòòòòòˆˆ65ôôôôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ88þ55Ô4568þ66665Ô4568ˆþ885Ô666Ô5ÔÔ588ˆþˆˆ85ÔÔ8866ÔÔ45Ô66Ôþ888ˆ8Ô4568886Ô5Ô4ÔÔÔÔ4þ
888ˆ864568ˆ8866Ô5ÔÔ44Ô55þ888ˆ864Ô8ˆˆˆ8866ÔÔ55455Ô66þò88ˆ8556ˆˆˆˆˆ8666ÔÔÔ54Ô5ÔÔÔÔÔþòòˆˆ64Ô8ˆˆˆˆˆˆ866666ÔÔÔ455555þòòòò556ˆˆˆˆˆˆˆ8888ˆ8654Ô5ôôôôôôôòòòòòÔ88888888688ˆˆ65ÔôôôôôôôôôôòòòòòòòÔÔÔÔÔ55Ô5Ô8ˆ8ôôôôôôôôôôôôòòòòòòòòòò5Ô4Ô4ÔÔ8ôôôôôôôôôôôôôôþòòòòòòòòòòò54Ôôôôôôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ55þˆˆ865þ88ˆˆ86ÔÔþÔÔÔ8ˆˆˆ86Ô4Ôþ885ÔÔ8ˆˆˆˆˆ866ÔÔþ8885Ô568ˆˆˆˆˆˆ886ÔÔ4þ
ˆˆˆ88Ô5ÔÔ8ˆˆˆˆˆˆˆˆ865ÔÔ55þˆˆˆˆˆ8654Ô8ˆˆˆˆˆˆˆˆˆˆˆ86Ô5Ô44þˆˆˆˆˆˆ885568ˆˆˆˆˆˆˆˆˆˆˆˆˆ886ÔÔþˆˆˆˆˆ88Ô456888ˆˆˆ866668ˆˆˆ8ôôôôôˆ8ˆ88665ÔÔ6666666ÔÔ4456ˆˆôôôôôôôò86Ô55555555555545ÔÔ54Ôôôôôôôôôôòò5ÔÔ55ÔÔ4444445ÔÔ555Ôôôôôôôôôôôòòòò4Ô5444ÔÔ4Ô56545Ôôôôôôôôôôôôôòòòòòòò4Ô4Ô4Ô565Ô5Ôôôôôôôôôôôôôôþòòòòòòòò44ÔÔ555ôôôôôôôôôôôôôþòòòòòòòòòÔ5Ôôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþˆˆþ888ˆþÔÔ8888ˆþÔÔ5ÔÔÔÔ6668ˆþÔÔÔ55555ÔÔÔ688ˆˆþÔÔ5Ô4555555Ô6688ˆˆˆˆˆþ
66Ô5Ô4Ô555ÔÔ66688666688ˆþ666Ô554455ÔÔÔ666Ô5Ô444Ô5Ô666þ6666ÔÔ5Ô455ÔÔ6ÔÔ545566Ô545ôôôþ6666866Ô5Ô45555Ô554Ô686866ÔôôôôÔÔ6686ÔÔÔ5Ô44ÔÔ5Ô45ÔÔ5ÔÔ55ôôôôôô5Ô66655ÔÔ55444444565ÔÔ554ôôôôôôô556Ô5556Ô55ÔÔÔ4Ô5655Ô5ÔÔôôôôôôôôòÔÔ5Ô5Ô6Ô5ÔÔÔ44ÔÔ5Ô545ôôôôôôôôôôòòò55Ô6Ô5Ô444Ô45ÔÔ456ôôôôôôôôôôôþòòòò5Ô44Ô5554ÔÔ568ôôôôôôôôôôþòòòòòÔÔÔÔÔ5668ˆôôôôôôôôôþ
òòòòòò5Ô688ôôôôôôôôôþòòòòòò88ôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5þÔÔþ444Ô4þ44444ÔÔ5Ôþ44444ÔÔÔ5Ô555þ444444444ÔÔ555555þÔÔ444ÔÔÔ44444Ô55Ô6666þ
ÔÔÔ44ÔÔ5Ô4Ô44ÔÔ56688888þ44Ô444ÔÔÔÔÔ444Ô5Ô688888888þ554444444444444ÔÔ668888886ôôþ66Ô5444Ô4Ô444444Ô5Ô6ÔÔ5ÔÔ5Ôôôôþ666Ô54ÔÔ555ÔÔ4444Ô565ÔÔÔ5Ô4ôôôô5Ô66Ô54Ô5555Ô444445Ô5Ô4Ô554ôôôôô5ÔÔÔÔÔ4555Ô44ÔÔ5Ô45Ô5Ô588ôôôôôôôò5Ô6Ô544Ô4Ô5ÔÔÔÔ54Ô6Ô88ˆôôôôôôôôþòò6Ô555Ô6688665568ˆˆ8ôôôôôôôþòòòÔ68ˆˆˆ88Ô4Ôˆˆ8ôôôôôôôþ
òòòòˆˆˆˆ6558ˆ8ôôôôôôþòòòòˆ8Ô46ˆ8ôôôôôþòòò8558ôôôôôþòòò5ôôôôþòòôôÿþ4þÔÔþ44Ôþ4444444Ôþ4454ÔÔÔÔ44ÔÔþ55455ÔÔ555455ÔÔþÔÔ5ÔÔÔ6ÔÔ55Ô5Ô6888þ888Ô66666Ô554ÔÔ6888ˆˆþ	88ˆ8886666ÔÔ5Ô45Ô6888ˆˆˆˆþ4458ˆˆ8866ÔÔ55544556888ˆˆ888þ55545Ô888866Ô5555Ô4Ô5688888665Ôþ55554568ˆ866ÔÔ5Ô55545Ô88866ÔÔÔôôò55ÔÔ68ˆˆ86ÔÔ6666ÔÔÔÔÔ888665ôôôôòòòòÔ886Ô555Ô68886654Ô88888ôôôôôþòòòò4Ô5Ô4ÔÔ68ˆ8865468ˆˆˆôôôôþòòòòÔ545Ô6888865Ô8ˆˆôôôôþ
òòòò45668888Ô45ˆˆôôôþòòòò688886Ô4Ôôôôþòòò68886Ôôôôþòò66ôôôôþòòôôÿþÔÔþ55ÔþÔÔ656666þ888Ô66888886þˆˆˆ88688ˆˆ886ÔÔ5þ5545ˆˆˆ88888886Ô5Ô68þ	ÔÔÔÔ5456ˆˆˆ8888866ÔÔ56ˆˆˆþ55ÔÔÔ5Ô4Ô888888886Ô54568ˆˆˆþò5555Ô45Ô66666666665Ô4588ˆˆˆˆþòòòò44Ô554444Ô5Ô6666Ô545688888þòòòòòò4Ô5ÔÔ6Ô54ÔÔ68886ÔÔÔ56686Ôþòòòòòòò88ˆˆˆ865ÔÔ68ˆ888Ô545Ô6ôôôþòòòòòòòˆˆˆ8ÔÔÔÔ6688886ÔÔ55ôôþòòòòòòˆ8Ô545ÔÔ668886Ô4ôôþ
òòòòò544555ÔÔ66666ôôþòòòòò44444455ôôôþòòòòò5ôôôôôôþòòòòôôôôþòòôôÿþ4þ445Ôþ554445Ô45þÔÔ5Ô4544ÔÔ4ÔÔ6þ54Ô555Ô5Ô4ÔÔ44445Ô668þ54Ô55555Ô4ÔÔ44ÔÔ5ÔÔ666þ
ò55Ô44444444444455Ô66665þòòò55ÔÔ444ÔÔ55Ô455Ô6686Ô5þòòòòò554Ô55ÔÔÔÔ54ÔÔÔ68886Ô5þòòòòòò54ÔÔ68888Ô545ÔÔ6888ˆ888þòòòòòòò4588ˆˆˆ865ÔÔ55ÔÔ6688ˆˆˆˆþòòòòòòòòò8ˆˆˆ86ÔÔ44ÔÔ5555Ô688ôôôþòòòòòòòò88655444Ô4Ô44445ôôôôþòòòòòòòòÔÔ455Ô5Ô6Ôôôôôôôþ
òòòòòòòò455ôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ55þÔ555ÔÔÔþÔÔÔÔ5ÔÔÔ88þ6666ÔÔ545Ô8ÔÔÔþ886666Ô54566ÔÔ544þˆ8866666Ô5ÔÔ66555444þˆ86666666ÔÔ566ÔÔ5544555þ88ÔÔÔÔÔÔ888Ô468866Ô5Ô555ÔÔþÔÔÔÔÔÔ5ÔÔÔ8ˆˆ8558ˆˆˆ8655554ÔÔ54Ô5ÔÔ6ÔÔÔÔ68ˆˆˆ646ˆˆ88ˆ86Ô5ÔÔ5ôôòòò55ÔÔ66688ˆˆ8ÔÔˆ8888ˆˆ86ÔÔÔôôôòòòòò55ÔÔ6688655ˆˆ8888ˆˆ655ôôôôôþòòòòò55ÔÔ6Ô558888888ˆ855ôôôôþòòòòò555Ô58ˆ88888ˆ85ôôôôþ
òòòòòÔÔÔˆ88888ˆ85ôôôþòòòò58ˆ8888ˆ8ôôôþòòò8ˆˆˆˆôôôôþòòòòôôôôþòòôôÿþˆˆþ8ˆˆˆ866þ8ˆˆˆˆ86Ô44þ66688ˆˆˆˆ6Ô4588þ55ÔÔ668ˆˆˆˆ8Ô458ˆˆþ	55ÔÔ44Ô5ÔÔ68ˆˆˆˆ85468ˆˆˆˆþÔÔÔÔÔ44555Ô668ˆˆ86Ô58ˆˆˆˆˆˆþòòò66655Ô455ÔÔ668654Ô8ˆ8ˆˆˆ555þòòòòò865Ô4455ÔÔÔÔ5458ˆˆ8ˆˆ855ˆˆˆòòòòòòÔ5Ô444Ô555Ô458ˆˆˆˆˆ8ÔÔ8ˆˆˆòòòòòòòò444444Ô4Ô568ˆˆˆˆ8646ˆôôôþòòòòòòòÔÔ4444Ô568ˆˆˆˆ8Ô46ôôôþòòòòòòò5ÔÔÔ5Ô6ˆˆˆˆ85Ôôôôþ
òòòòòò5555Ô8888Ôôôôôþòòòòòò55ÔÔôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþˆˆþ555ÔˆˆˆˆþÔÔ444Ô55ˆˆˆˆˆˆþ44ÔÔÔ5ÔÔÔ44455Ôˆˆˆˆˆˆþ	55Ô455Ô5Ô555Ô44Ô5ÔˆˆˆÔÔÔþòò456888886Ô5Ô44Ô555Ô5Ô444þòòòòˆ8ˆˆˆ88Ô55444ÔÔ555Ô4455þòòòòò88ˆˆ8Ô55ÔÔ44444Ô44455Ô44þòòòòòòˆˆ65Ô444Ô4Ô4444Ô5555Ô45Ô55òòòòòòòò4Ô544ÔÔÔÔÔÔÔ555Ô55ÔÔ5ÔôÔòòòòòòòòòò54Ô555555555ÔÔ5Ô4ôôôôôþòòòòòòòòò455ÔÔÔ6ÔÔÔÔÔôôôôôôôþòòòòòòòòò5555ôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþÔþ55þ555555ÔÔ555þ5Ô4Ô5555555Ô55555þ65Ô455ÔÔÔÔ5555555555þ
6ÔÔÔÔ5Ô688866Ô55555Ô5Ô55þòÔ54ÔÔ888ˆˆ88Ô55ÔÔÔ5ÔÔ5555þòò54568ˆˆˆ88Ô5Ô4Ô4ÔÔÔ5Ô55555þòòòò68ˆˆˆ8854ÔÔÔ44Ô55555555Ô555þòòòòòˆˆˆˆ8ÔÔ6Ô54Ô555555555ÔÔ55Ô5òòòòòòòˆ8Ô6ˆ654Ô5ÔÔÔÔÔÔ5ÔÔôôôôôôòòòòòòòòòÔˆˆÔ4Ô55ÔÔÔ5ôôôôôôôôôôôòòòòòòòòòòò8ÔÔ4ÔÔÔôôôôôôôôôôôôôôþòòòòòòòòòòòò5Ôôôôôôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5þ6Ô5544þÔ6Ô55Ô44444þ55ÔÔÔÔ554444444þ555ÔÔ6Ô55Ô444444ÔÔÔþ555ÔÔ6ÔÔ55544ÔÔÔ4ÔÔ5555þÔ555555ÔÔÔÔ5Ô45ÔÔ544Ô5555555þÔÔ55ÔÔ555ÔÔ55ÔÔ66Ô54ÔÔ555555Ô555Ô5Ô444Ô5ÔÔÔ54Ôˆˆ654Ô55555ÔÔ4Ô5ôÔòò4Ô44Ô5Ô6ÔÔ58ˆ654Ô555Ô45ÔôôôôôôòòòÔ445Ô66ÔÔ5865Ô4ÔÔ4ÔÔôôôôôôôôôòòòòòÔÔÔÔÔ5ÔÔ6Ô5ÔÔÔ56ôôôôôôôôôôôòòòòòòòÔ5554Ô86ÔÔÔ6ôôôôôôôôôôôôôòòòòòòòòòò5568888ôôôôôôôôôôôôôôôþòòòòòòòòòòò88ˆôôôôôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5þ6544þ8654Ô888þ866545Ô888866þ88665ÔÔÔ688886Ô555þ686Ô5Ô45Ô68ˆˆ86Ô555Ô66þ666ÔÔ5Ô4ÔÔÔ8ˆˆˆ8Ô5555Ô68ÔÔþ66ÔÔ5544Ô5568ˆˆ8Ô5555Ô688Ô68þ6ÔÔ5Ô44444Ô5Ô666Ô555Ô68ˆˆÔôôôþ6ÔÔ55Ô44444ÔÔ4455555ÔÔ68ˆ8ôôôôô55Ô5544444Ô5555Ô455ÔÔÔ88ˆôôôôôôôÔ5Ô544444Ô5ÔÔÔ5Ô45Ô6688ôôôôôôôôôò55Ô4444Ô5ÔÔ555Ô5Ô6888ôôôôôôôôôôòòòÔÔ5Ô4Ô5Ô555545668ôôôôôôôôôôôôòòòòòò545Ô5Ô555ÔÔ66ôôôôôôôôôôôôôþòòòòòòò55555ÔÔÔÔôôôôôôôôôôôôþòòòòòòòòÔ54Ôôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5455þ6Ô54568ˆˆþÔÔ5ÔÔÔ68ˆ8888þ5Ô55ÔÔ5Ô6888886888þ5555Ô4ÔÔÔÔ666666886ÔÔþ
5555Ô4Ô5555555ÔÔ6686Ô44þ555ÔÔ4444444Ô44Ô5ÔÔ666548ˆþ55ÔÔ4444445555554Ô5Ô6Ô54Ôôôþ5ÔÔÔ44444Ô5ÔÔÔÔ554Ô5ÔÔ5Ôôôôôþ55ÔÔ44444Ô5ÔÔ555554Ô5554ôôôôôþ5555ÔÔ4444455ÔÔÔÔ5554Ô55ôôôôôôô555ÔÔ4444ÔÔ45ÔÔ44Ô55Ô4Ô5ôôôôôôôô55Ô44ÔÔ5555ÔÔ5Ô4Ô555Ô4Ôôôôôôôôôôòò55Ô5Ô66Ô45ÔÔ55ÔÔÔ5Ô4ôôôôôôôôôôþòòò66865Ô8886866Ô5ôôôôôôôôôôþòòòòò4688888865ôôôôôôôôôþ
òòòòò8ˆˆ886Ôôôôôôôôôþòòòòòˆ886ôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5555þ5555Ô4ÔÔÔþ4ÔÔ5ÔÔÔ4ÔÔ5ÔÔþÔ4ÔÔÔÔÔ45555Ô555þ5Ô4444ÔÔ55Ô55555555þ55Ô4444Ô55Ô555Ô555555þ	ÔÔ5Ô4444Ô5555544Ô555555ÔÔþ6Ô5Ô44444Ô55544Ô44555555Ô6þÔÔÔ4444ÔÔ4Ô55ÔÔÔÔ4Ô555555ôôþ6654444Ô55545Ô5ÔÔ44Ô55555ôôôôþ886Ô5ÔÔÔ5Ô66ÔÔÔ666Ô555Ô55Ôôôôôôˆˆ866ÔÔÔ668ˆ6ÔÔ88888866Ô55ôôôôôôòòˆˆ88888ˆˆ8Ô58ˆˆˆˆˆ886Ô5ôôôôôôôþòòò888ˆˆˆ648ˆ888ˆˆˆ8Ôôôôôôôôþòòòòˆˆ856ˆ88888ˆ86ôôôôôôþ
òòòòÔ5888888ˆˆ6ôôôôôþòòòòˆ88888ˆôôôôôþòòò888ˆôôôôôþòòòˆôôôôþòòôôÿþ8þˆˆˆþ888ˆˆ8þ888888ˆ85þˆˆ88888ˆ8556þ88ˆˆ8888ˆˆ64Ô8ˆþ888ˆ88888ˆ85568ˆˆˆþ66888ˆ888ˆ88ÔÔ8ˆˆˆˆˆþ
6666558ˆˆˆ888Ô4Ô88ˆˆˆˆ88þ66665458ˆ886665Ô66888886666ˆþÔÔ665Ô45886Ô56Ô45ÔÔ666ÔÔÔÔÔ8ˆˆˆÔÔÔ65Ô5ÔÔ86555Ô5455ÔÔÔ5555568ˆôôòÔ6Ô45Ô566Ô555Ô5455555ÔÔÔ5Ô6ôôôôòòÔÔ554Ô6Ô5Ô5Ô5Ô4555Ô444Ô5ôôôôôôòòòòÔ4566555ÔÔ54Ô4Ô44444ÔôôôôôôôòòòòòÔÔ6Ô555Ô5Ô444444444ôôôôôôôôòòòòòòò6ÔÔÔÔÔ5444444Ô4ôôôôôôôôôôþòòòòòòÔ6ÔÔ5Ô4444ÔÔÔôôôôôôôôôþòòòòòò655Ô4ÔÔÔÔ5ôôôôôôôôþ
òòòòòò5ÔÔÔÔ5ôôôôôôôôþòòòòòòò55ôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ88þ888þ88888þˆˆˆ88888þ88ˆˆ8888ˆ88þ66888ˆ88ˆ86Ô4þ6666Ô68ˆˆ855Ô5ÔÔÔþ66665ÔÔ8865ÔÔ5Ô555555þ
ÔÔ66544Ô66Ô5Ô554555ÔÔ44Ô5þ55Ô6Ô44Ô5ÔÔ55Ô5ÔÔ5ÔÔÔ44Ô555Ôþ4445Ô65Ô4Ô5ÔÔÔ455455ÔÔ44Ô555ôôÔ444456ÔÔÔ4ÔÔ45Ô5545555Ô4Ô55Ôôôô4444ÔÔ65Ô44Ô4Ô4554Ô555Ô4Ô55Ôôôôôò4Ô45Ô6555554455ÔÔ555Ô4Ô55ôôôôôôòò44566ÔÔ55555ÔÔÔ555Ô4455ôôôôôôôòòòòÔ886666Ô65ÔÔ5Ô554455ôôôôôôôôþòòò8888886Ô45ÔÔ55ÔÔÔ5ôôôôôôôþòòò88885Ô5ÔÔÔ5Ô4Ôôôôôôôôþ
òòò6Ô45ÔÔÔ5Ô4ÔôôôôôôþòòòòÔÔÔ54ÔÔôôôôôþòòòòò44ôôôôôþòòòòôôôôþòòôôÿþˆþ888þ88888þ6686Ô55þÔÔ665Ô4ÔÔÔþ445Ô654Ô5Ô655ÔÔþÔÔ45ÔÔ45Ô66Ô5Ô54444þˆÔÔÔ45654Ô66Ô4Ô5444ÔÔ44Ôþ88ÔÔ54565ÔÔÔÔ4554Ô555545ÔÔ5þˆˆˆ86654Ô654Ô5Ô55Ô55555ÔÔÔ65ôþˆˆˆˆˆˆ8654Ô6Ô5Ô5ÔÔ5ÔÔÔÔ554ÔÔôôôˆˆˆˆˆˆˆ88Ô4Ô666Ô545Ô66ÔÔ545ÔôôôôòÔˆˆˆˆˆˆ8Ô45Ô6Ô55Ô666ÔÔ5ÔÔÔôôôôôòòòˆˆˆˆˆ86545Ô4Ô68886ÔÔÔ45ôôôôôôþòòòÔÔˆ86Ô55Ô68ˆ886ÔÔ5ÔôôôôôôþòòòÔ88688ˆˆˆ8866ÔÔ5ôôôôôþ
òòòòˆˆˆˆˆ886666ôôôôôþòòòòòò86666ôôôôôþòòòòòò8ôôôôôþòòòòôôôôþòòôôÿþ5þ44þÔÔ545þ66Ô545ÔÔþ6666Ô545ÔÔ556þ6666666Ô45ÔÔ5Ô5455þ666666666ÔÔ555545Ô66666þ66ÔÔ66ÔÔ6688654Ô4ÔÔ688886Ô4Ôþ55ÔÔ6ÔÔÔ5ÔÔ68ˆˆ8Ô55Ô888ˆ88865588òÔÔÔ555555Ô68ˆˆ86688ˆˆˆˆˆ88Ô4Ôôôòòò5ÔÔ44445Ô8ˆˆ8ˆˆˆˆˆˆˆˆˆ865Ôôôôòòòòòò5554Ô56888ˆˆˆˆˆˆˆˆˆ86ôôôôôþòòòòòòò5455Ô668888ˆˆˆˆˆ8ôôôôþòòòòòòòòÔ5ÔÔÔ6688ˆˆˆôôôôþ
òòòòòòòò5ÔÔÔ668ôôôôôþòòòòòòòòÔôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5þ444þÔÔ544Ôþ555ÔÔ5445Ô68þ44Ô5555Ô5Ô4ÔÔ8ˆˆ6ÔÔþ44444Ô4Ô5555554456ˆˆ6ÔÔÔ68ˆþò4444Ô55555555ÔÔÔ66ÔÔ5Ô68ˆˆˆˆþòòòò555ÔÔÔ66Ô54ÔÔÔ555Ô66ˆˆˆˆˆˆþòòòòòòò66866Ô5444ÔÔ55Ô688ˆˆˆˆ86Ôòòòòòòòòòò6Ô5ÔÔ444455Ô6688ˆˆˆ86ôòòòòòòòòòòòòÔ4ÔÔ444Ô5ÔÔ66888ˆôôôþòòòòòòòòòòòòÔÔ4Ô44Ô55ÔÔ6ôôôôþòòòòòòòòòòò5Ô5Ô44ôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþÔÔ5þ5555Ô5Ô55þ55Ô4Ô5555Ô555554ÔþÔÔ6ÔÔ5Ô4Ô5555555554Ô5Ô5þ	òÔ6ÔÔ554Ô555ÔÔÔ55Ô444Ô566þòòòò554ÔÔ555Ô555ÔÔÔ5Ô8888ÔÔþòòòòòòòÔ5555ÔÔ4445568888Ô545Ôþòòòòòòòòò44Ô5554ÔÔ68886Ô545ÔÔ6þòòòòòòòòòòòÔÔÔÔÔÔ888665Ô4Ô55ÔÔÔþòòòòòòòòòòòò54ÔÔÔ66Ô55Ô44ÔÔ555ôôòòòòòòòòòòòòòòÔÔˆÔÔ55Ô444ôôôôôôôþòòòòòòòòòòòòòˆÔ555ôôôôôôôôôôþòòòòòòòòòòòòôôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþÔÔ555þÔÔÔ55Ô5555þ8868ÔÔ5544ÔÔ55ÔÔþ886Ô86886Ô5Ô44ÔÔ44444þ	88ÔÔ6ÔÔ6ˆˆ86Ô5Ô444444455þÔÔÔÔ55Ô6ˆˆˆ86Ô5555ÔÔ456ˆˆ8þòòò666Ô6ˆˆˆˆ8666ÔÔ5456ˆˆ8ˆˆþòòòòò6Ô8Ôˆˆˆˆˆˆ8865ÔÔ8ˆˆˆˆ88þòòòòòòò8Ôˆˆˆˆˆˆ8654Ô88ˆˆ865Ô44þòòòòòòòòòÔˆˆˆ86ÔÔ568886Ô544444Ô5òòòòòòòòòò886ÔÔÔ5Ô66Ô554Ô555ôôôôòòòòòòòòòòòò54ÔÔÔÔÔÔ54Ô5ôôôôôôôôòòòòòòòòòòòòò55ÔÔÔ5Ô4ôôôôôôôôôôôþòòòòòòòòòòòòòÔ554ôôôôôôôôôôôþòòòòòòòòòòòòÔôôôôôôôôôôôþ
òòòòòòòòòòôôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿþ5þ555ÔÔþÔÔÔ55ÔÔÔþÔÔ8ÔÔ45Ô6ÔÔ5þ668Ô8654Ô6886ÔÔ5þ55868ˆˆ85Ô68ˆ886ÔÔ5þ66588ˆˆˆ8556ˆˆˆ8866Ô5þ	ÔÔ668688ˆˆ8556ˆˆˆˆ886ÔÔÔÔþÔÔÔ6655Ô8888558ˆˆˆˆˆ88ÔÔÔ68þòÔ6ÔÔ45Ô6888Ô58ˆˆˆˆˆ86545ÔÔ54þòòò4Ô456688Ô4Ô688886Ô5455Ô45ÔÔ5þòòòòÔ5Ô8686545Ô666Ô5ÔÔ554ÔÔ686ôôòòòòòò88886545ÔÔÔ5Ô4Ô554568ôôôôôòòòòòòòò88Ô54555Ô4Ô555456ôôôôôôôòòòòòòòòò6ÔÔ4ÔÔ44Ô55Ô45ôôôôôôôôôòòòòòòòòòò5Ô444Ô5555ÔôôôôôôôôôôôþòòòòòòòòòòÔÔÔ5555ôôôôôôôôôôôþòòòòòòòòòò5555ôôôôôôôôôôþ
òòòòòòòòòò5ôôôôôôôôôþòòòòòòòòôôôôôôôôþòòòòòòôôôôôôþòòòòôôôôþòòôôÿÿÿÿÿÿÿÿ